In [1]:
%load_ext cudf.pandas

In [2]:
import sys
import os

sys.path.insert(0, os.path.abspath("/home/ElasticNotebook"))
%load_ext ElasticNotebook
import cudf

Enabled rmm statistics

# Data Visualization

The purpose of this notebook is to practice data visualization, and hopefully communicate some best-practices along the way.


# Please upvote if you find this useful

Some sources I'd reccomend for data visualization principles are:

- Storytelling with data, C. Knaflic

- The visual display of quantitative information, E. Tufte

- Better data visualizations, J. Schwabish


I have other notebooks that also incoroprate some nice visuals:

**UK COVID-19 Vaccination Data Visualization**

https://www.kaggle.com/joshuaswords/uk-covid-19-vaccination-progress-data-vis


**Exploratory Data Visualization - Student Performance**

https://www.kaggle.com/joshuaswords/data-visualisation-student-results

**HR Data Set - Visuals & Predictions**

https://www.kaggle.com/joshuaswords/awesome-hr-data-visualization-prediction


**Visuals & Customer Segmentation**

https://www.kaggle.com/joshuaswords/data-visualization-clustering-mall-data


As well as learning from other Kagglers who enjoy data viz.

With that said, let's go...

In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load
# %load_ext cudf.pandas
import numpy as np  # linear algebra
import os

# STEFANOS: Conditionally import Modin Pandas
if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    # STEFANOS: Import Modin Pandas
    import os

    os.environ["MODIN_ENGINE"] = "ray"
    import ray

    ray.init(
        num_cpus=int(os.environ["MODIN_CPUS"]),
        runtime_env={"env_vars": {"__MODIN_AUTOIMPORT_PANDAS__": "1"}},
    )
    import modin.pandas as pd
else:
    # STEFANOS: Import regular Pandas
    import pandas as pd

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os

for dirname, _, filenames in os.walk("../input"):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
# Importing libs

# STEFANOS: Disable unneeded modules
# from sklearn.preprocessing import StandardScaler
# from sklearn.cluster import KMeans, AffinityPropagation
# import matplotlib.pyplot as plt
# import seaborn as sns
# %matplotlib inline
import warnings

warnings.filterwarnings("ignore")
# import plotly as py
# import plotly.graph_objs as go
import os

# py.offline.init_notebook_mode(connected = True)
# print(os.listdir("../input"))
# STEFANOS: Disable unneeded modules
# import missingno as msno
# plt.rcParams['figure.dpi'] = 140

In [5]:
%%time
### cell 0 ###

df = pd.read_csv(
    "/home/dias-benchmarks/notebooks/joshuaswords/netflix-data-visualization/input/netflix-shows/netflix_titles.csv"
)

df.head(3)

CPU times: user 39.2 ms, sys: 61.3 ms, total: 101 ms
Wall time: 93.9 ms

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,<NA>,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,<NA>,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",<NA>,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 0 ##
pd_df["show_id"] = df["show_id"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_df["type"] = df["type"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_df["title"] = df["title"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_df["director"] = df["director"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_df["cast"] = df["cast"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_df["country"] = df["country"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_df["date_added"] = df["date_added"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_df["release_year"] = df["release_year"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_df["rating"] = df["rating"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_df["duration"] = df["duration"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_df["listed_in"] = df["listed_in"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_df["description"] = df["description"]

# -- STEFANOS -- Replicate Data

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df["show_id"] = df["show_id"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df["type"] = df["type"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df["title"] = df["title"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df["director"] = df["director"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df["cast"] = df["cast"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df["country"] = df["country"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df["date_added"] = df["date_added"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df["release_year"] = df["release_year"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df["rating"] = df["rating"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df["duration"] = df["duration"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df["listed_in"] = df["listed_in"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df["description"] = df["description"]

In [6]:
%%time
### cell 1 ###

factor = 500
df = pd.concat([df] * factor, ignore_index=True)

CPU times: user 592 ms, sys: 157 ms, total: 749 ms
Wall time: 695 ms

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 1 ##
pd_df["show_id"] = df["show_id"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_df["type"] = df["type"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_df["title"] = df["title"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_df["director"] = df["director"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_df["cast"] = df["cast"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_df["country"] = df["country"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_df["date_added"] = df["date_added"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_df["release_year"] = df["release_year"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_df["rating"] = df["rating"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_df["duration"] = df["duration"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_df["listed_in"] = df["listed_in"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_df["description"] = df["description"]

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df["title"] = df["title"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df["release_year"] = df["release_year"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df["description"] = df["description"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df["duration"] = df["duration"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df["type"] = df["type"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df["director"] = df["director"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df["listed_in"] = df["listed_in"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df["show_id"] = df["show_id"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df["cast"] = df["cast"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df["date_added"] = df["date_added"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df["rating"] = df["rating"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df["country"] = df["country"]

In [7]:
%%time
### cell 2 ###

# Missing data

for i in df.columns:
    null_rate = df[i].isna().sum() / len(df) * 100
    if null_rate > 0:
        print("{} null rate: {}%".format(i, round(null_rate, 2)))

director null rate: 29.91%
cast null rate: 9.37%
country null rate: 9.44%
date_added null rate: 0.11%
rating null rate: 0.05%
duration null rate: 0.03%
CPU times: user 27.2 ms, sys: 15.1 ms, total: 42.3 ms
Wall time: 37.9 ms

- 5 columns have missing values, with Director missing 1/3 of the time

# Dealing with the missing data

- This is always scenario dependant, but in this case, I will:
    - replace blank countries with the mode (most common) country
    - I want to keep director as it could be interesting to look at a certain director's films
    - I want to keep cast as it could be interesting to look at a certain cast's films

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df["title"] = df["title"]

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df["release_year"] = df["release_year"]

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df["description"] = df["description"]

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df["duration"] = df["duration"]

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df["type"] = df["type"]

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df["director"] = df["director"]

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df["listed_in"] = df["listed_in"]

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df["show_id"] = df["show_id"]

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df["cast"] = df["cast"]

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df["date_added"] = df["date_added"]

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df["rating"] = df["rating"]

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df["country"] = df["country"]

In [8]:
%%time
### cell 3 ###

# Replacments

df["country"] = df["country"].fillna(df["country"].mode()[0])


df["cast"].replace(np.nan, "No Data", inplace=True)
df["director"].replace(np.nan, "No Data", inplace=True)

# Drops

df.dropna(inplace=True)

# Drop Duplicates

# STEFANOS: Remove this because it makes the dataset same as the original.
# df.drop_duplicates(inplace= True)

CPU times: user 231 ms, sys: 92.9 ms, total: 324 ms
Wall time: 327 ms

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 3 ##
pd_df["title"] = df["title"]

In [ ]:
%%time
## Transfer_post 3 ##
pd_df["release_year"] = df["release_year"]

In [ ]:
%%time
## Transfer_post 3 ##
pd_df["description"] = df["description"]

In [ ]:
%%time
## Transfer_post 3 ##
pd_df["duration"] = df["duration"]

In [ ]:
%%time
## Transfer_post 3 ##
pd_df["type"] = df["type"]

In [ ]:
%%time
## Transfer_post 3 ##
pd_df["director"] = df["director"]

In [ ]:
%%time
## Transfer_post 3 ##
pd_df["listed_in"] = df["listed_in"]

In [ ]:
%%time
## Transfer_post 3 ##
pd_df["show_id"] = df["show_id"]

In [ ]:
%%time
## Transfer_post 3 ##
pd_df["cast"] = df["cast"]

In [ ]:
%%time
## Transfer_post 3 ##
pd_df["date_added"] = df["date_added"]

In [ ]:
%%time
## Transfer_post 3 ##
pd_df["rating"] = df["rating"]

In [ ]:
%%time
## Transfer_post 3 ##
pd_df["country"] = df["country"]

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df["show_id"] = df["show_id"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df["type"] = df["type"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df["title"] = df["title"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df["director"] = df["director"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df["cast"] = df["cast"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df["country"] = df["country"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df["date_added"] = df["date_added"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df["release_year"] = df["release_year"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df["rating"] = df["rating"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df["duration"] = df["duration"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df["listed_in"] = df["listed_in"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df["description"] = df["description"]

In [9]:
%%time
### cell 4 ###

df.isnull().sum()

CPU times: user 21.2 ms, sys: 716 µs, total: 21.9 ms
Wall time: 17.5 ms

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df["show_id"] = df["show_id"]

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df["type"] = df["type"]

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df["title"] = df["title"]

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df["director"] = df["director"]

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df["cast"] = df["cast"]

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df["country"] = df["country"]

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df["date_added"] = df["date_added"]

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df["release_year"] = df["release_year"]

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df["rating"] = df["rating"]

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df["duration"] = df["duration"]

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df["listed_in"] = df["listed_in"]

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df["description"] = df["description"]

In [10]:
%%time
### cell 5 ###

df.info()

<class 'cudf.core.dataframe.DataFrame'>
Index: 4395000 entries, 0 to 4403499
Data columns (total 12 columns):
 #   Column        Dtype
---  ------        -----
 0   show_id       object
 1   type          object
 2   title         object
 3   director      object
 4   cast          object
 5   country       object
 6   date_added    object
 7   release_year  int64
 8   rating        object
 9   duration      object
 10  listed_in     object
 11  description   object
dtypes: int64(1), object(11)
memory usage: 1.7+ GB
CPU times: user 9.53 ms, sys: 267 µs, total: 9.8 ms
Wall time: 8.21 ms

# Missing values dealt with, but the date isn't quite right yet...

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df["rating"] = df["rating"]

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df["type"] = df["type"]

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df["date_added"] = df["date_added"]

In [11]:
%%time
### cell 6 ###

df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")


df["month_added"] = df["date_added"].dt.month
df["index"] = df["date_added"].dt.month_name()
df["year_added"] = df["date_added"].dt.year

df.head(3)

CPU times: user 581 ms, sys: 120 ms, total: 701 ms
Wall time: 712 ms

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,month_added,index,year_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,No Data,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",9,September,2021
1,s2,TV Show,Blood & Water,No Data,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",9,September,2021
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,9,September,2021

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 6 ##
pd_df["month_added"] = df["month_added"]

In [ ]:
%%time
## Transfer_post 6 ##
pd_df["year_added"] = df["year_added"]

In [ ]:
%%time
## Transfer_post 6 ##
pd_df["date_added"] = df["date_added"]

In [ ]:
%%time
## Transfer_post 6 ##
pd_df["index"] = df["index"]

# Okay, let's visualize

# Where possible, I'll use the Netflix brand colours

https://brand.netflix.com/en/assets/brand-symbol/


Using a consistent color palette is a great way to give your work credibility. It looks professional, and keeps the reader engaged. 

It's an easy-to-implement tip that really helps.

In [12]:
# Palette
# STEFANOS: Disable plotting
# sns.palplot(['#221f1f', '#b20710', '#e50914','#f5f5f1'])

# plt.title("Netflix brand palette ",loc='left',fontfamily='serif',fontsize=15,y=1.2)
# plt.show()

# Netflix through the years

Netflix started as DVD rentals, and now they have an audience of over 150m people - this is their story...

Timeline code from Subin An's awesome notebook
https://www.kaggle.com/subinium/awesome-visualization-with-titanic-dataset

In [13]:
# STEFANOS: Disable plotting

# # Timeline code from Subin An's awesome notebook
# # https://www.kaggle.com/subinium/awesome-visualization-with-titanic-dataset


# from datetime import datetime

# ## these go on the numbers below
# tl_dates = [
#     "1997\nFounded",
#     "1998\nMail Service",
#     "2003\nGoes Public",
#     "2007\nStreaming service",
#     "2016\nGoes Global",
#     "2021\nNetflix & Chill"
# ]

# tl_x = [1, 2, 4, 5.3, 8,9]

# ## these go on the numbers
# tl_sub_x = [1.5,3,5,6.5,7]


# tl_sub_times = [
#     "1998","2000","2006","2010","2012"
# ]

# tl_text = [
#     "Netflix.com launched",
#     "Starts\nPersonal\nRecommendations","Billionth DVD Delivery","Canadian\nLaunch","UK Launch\n(my birthplace)"]


# # Set figure & Axes
# fig, ax = plt.subplots(figsize=(15, 4), constrained_layout=True)
# ax.set_ylim(-2, 1.75)
# ax.set_xlim(0, 10)


# # Timeline : line
# ax.axhline(0, xmin=0.1, xmax=0.9, c='#4a4a4a', zorder=1)


# # Timeline : Date Points
# ax.scatter(tl_x, np.zeros(len(tl_x)), s=120, c='#4a4a4a', zorder=2)
# ax.scatter(tl_x, np.zeros(len(tl_x)), s=30, c='#fafafa', zorder=3)
# # Timeline : Time Points
# ax.scatter(tl_sub_x, np.zeros(len(tl_sub_x)), s=50, c='#4a4a4a',zorder=4)

# # Date Text
# for x, date in zip(tl_x, tl_dates):
#     ax.text(x, -0.55, date, ha='center',
#             fontfamily='serif', fontweight='bold',
#             color='#4a4a4a',fontsize=12)


# # Stemplot : vertical line
# levels = np.zeros(len(tl_sub_x))
# levels[::2] = 0.3
# levels[1::2] = -0.3
# markerline, stemline, baseline = ax.stem(tl_sub_x, levels, use_line_collection=True)
# plt.setp(baseline, zorder=0)
# plt.setp(markerline, marker=',', color='#4a4a4a')
# plt.setp(stemline, color='#4a4a4a')

# # Text
# for idx, x, time, txt in zip(range(1, len(tl_sub_x)+1), tl_sub_x, tl_sub_times, tl_text):
#     ax.text(x, 1.3*(idx%2)-0.5, time, ha='center',
#             fontfamily='serif', fontweight='bold',
#             color='#4a4a4a' if idx!=len(tl_sub_x) else '#b20710', fontsize=11)

#     ax.text(x, 1.3*(idx%2)-0.6, txt, va='top', ha='center',
#         fontfamily='serif',color='#4a4a4a' if idx!=len(tl_sub_x) else '#b20710')


# # Spine
# for spine in ["left", "top", "right", "bottom"]:
#     ax.spines[spine].set_visible(False)

# # Ticks
# ax.set_xticks([])
# ax.set_yticks([])

# # Title
# ax.set_title("Netflix through the years", fontweight="bold", fontfamily='serif', fontsize=16, color='#4a4a4a')
# ax.text(2.4,1.57,"From DVD rentals to a global audience of over 150m people - is it time for Netflix to Chill?", fontfamily='serif', fontsize=12, color='#4a4a4a')

# plt.show()

# Content - Let's explore

Now we've seen how Netflix came to dominate our TV screens, let's have a look at the content they offer...

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df["type"] = df["type"]

In [14]:
%%time
### cell 7 ###

# For viz: Ratio of Movies & TV shows

x = df.groupby(["type"])["type"].count()
y = len(df)
r = (x / y).round(2)

mf_ratio = pd.DataFrame(r).T

CPU times: user 22.5 ms, sys: 8.74 ms, total: 31.2 ms
Wall time: 28.6 ms

In [ ]:
pd_mf_ratio = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 7 ##
pd_mf_ratio["Movie"] = mf_ratio["Movie"]

In [ ]:
%%time
## Transfer_post 7 ##
pd_mf_ratio["TV Show"] = mf_ratio["TV Show"]

In [ ]:
%%time
## Transfer_post 7 ##
pd_x = x

In [ ]:
pd_mf_ratio = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 8 ##
pd_mf_ratio["Movie"] = mf_ratio["Movie"]

In [ ]:
%%time
## Transfer_pre 8 ##
pd_mf_ratio["TV Show"] = mf_ratio["TV Show"]

In [15]:
%%time
### cell 8 ###

# STEFANOS: Disable plotting


# fig, ax = plt.subplots(1,1,figsize=(6.5, 2.5))

# ax.barh(mf_ratio.index, mf_ratio['Movie'],
#         color='#b20710', alpha=0.9, label='Male')
# ax.barh(mf_ratio.index, mf_ratio['TV Show'], left=mf_ratio['Movie'],
#         color='#221f1f', alpha=0.9, label='Female')

# ax.set_xlim(0, 1)
# ax.set_xticks([])
# ax.set_yticks([])
# #ax.set_yticklabels(mf_ratio.index, fontfamily='serif', fontsize=11)


# # movie percentage
# for i in mf_ratio.index:
#     ax.annotate(f"{int(mf_ratio['Movie'][i]*100)}%",
#                    xy=(mf_ratio['Movie'][i]/2, i),
#                    va = 'center', ha='center',fontsize=40, fontweight='light', fontfamily='serif',
#                    color='white')

#     ax.annotate("Movie",
#                    xy=(mf_ratio['Movie'][i]/2, -0.25),
#                    va = 'center', ha='center',fontsize=15, fontweight='light', fontfamily='serif',
#                    color='white')


# for i in mf_ratio.index:
#     ax.annotate(f"{int(mf_ratio['TV Show'][i]*100)}%",
#                    xy=(mf_ratio['Movie'][i]+mf_ratio['TV Show'][i]/2, i),
#                    va = 'center', ha='center',fontsize=40, fontweight='light', fontfamily='serif',
#                    color='white')
#     ax.annotate("TV Show",
#                    xy=(mf_ratio['Movie'][i]+mf_ratio['TV Show'][i]/2, -0.25),
#                    va = 'center', ha='center',fontsize=15, fontweight='light', fontfamily='serif',
#                    color='white')


# # Title & Subtitle
# fig.text(0.125,1.03,'Movie & TV Show distribution', fontfamily='serif',fontsize=15, fontweight='bold')
# fig.text(0.125,0.92,'We see vastly more movies than TV shows on Netflix.',fontfamily='serif',fontsize=12)

# for s in ['top', 'left', 'right', 'bottom']:
#     ax.spines[s].set_visible(False)


# #ax.legend(loc='lower center', ncol=3, bbox_to_anchor=(0.5, -0.06))

# # Removing legend due to labelled plot
# ax.legend().set_visible(False)
# plt.show()


for i in mf_ratio.index:
    _ = int(mf_ratio["Movie"][i] * 100)
    _ = mf_ratio["Movie"][i] / 2
    _ = mf_ratio["Movie"][i] / 2

for i in mf_ratio.index:
    _ = int(mf_ratio["TV Show"][i] * 100)
    _ = mf_ratio["Movie"][i] + mf_ratio["TV Show"][i] / 2
    _ = mf_ratio["Movie"][i] + mf_ratio["TV Show"][i] / 2

CPU times: user 44.4 ms, sys: 13.3 ms, total: 57.7 ms
Wall time: 59.2 ms

# By Country

So we now know there are much more movies than TV shows on Netflix (which surprises me!).

What about if we look at content by country? 

I would imagine that the USA will have the most content. I wonder how my country, the UK, will compare?

In [ ]:
%%time
## Transfer_pre 9 ##
pd_x = x

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df["listed_in"] = df["listed_in"]

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df["country"] = df["country"]

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df["rating"] = df["rating"]

In [16]:
%%time
### cell 9 ###

# Quick feature engineering

# Helper column for various plots
df["count"] = 1

# Many productions have several countries listed - this will skew our results , we'll grab the first one mentioned

# Lets retrieve just the first country
df["first_country"] = df["country"].apply(lambda x: x.split(",")[0])
df["first_country"].head()

# Rating ages from this notebook: https://www.kaggle.com/andreshg/eda-beginner-to-expert-plotly (thank you!)

ratings_ages = {
    "TV-PG": "Older Kids",
    "TV-MA": "Adults",
    "TV-Y7-FV": "Older Kids",
    "TV-Y7": "Older Kids",
    "TV-14": "Teens",
    "R": "Adults",
    "TV-Y": "Kids",
    "NR": "Adults",
    "PG-13": "Teens",
    "TV-G": "Kids",
    "PG": "Older Kids",
    "G": "Kids",
    "UR": "Adults",
    "NC-17": "Adults",
}

df["target_ages"] = df["rating"].replace(ratings_ages)
df["target_ages"].unique()

# Genre

df["genre"] = df["listed_in"].apply(
    lambda x: x.replace(" ,", ",").replace(", ", ",").split(",")
)

# Reducing name length

df["first_country"].replace("United States", "USA", inplace=True)
df["first_country"].replace("United Kingdom", "UK", inplace=True)
df["first_country"].replace("South Korea", "S. Korea", inplace=True)

CPU times: user 12.1 s, sys: 924 ms, total: 13 s
Wall time: 13 s

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 9 ##
pd_df["count"] = df["count"]

In [ ]:
%%time
## Transfer_post 9 ##
pd_df["genre"] = df["genre"]

In [ ]:
%%time
## Transfer_post 9 ##
pd_df["first_country"] = df["first_country"]

In [ ]:
%%time
## Transfer_post 9 ##
pd_df["target_ages"] = df["target_ages"]

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df["count"] = df["count"]

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df["first_country"] = df["first_country"]

In [17]:
%%time
### cell 10 ###

data = df.groupby("first_country")["count"].sum().sort_values(ascending=False)[:10]

# STEFANOS: Disable plotting

# # Plot

# color_map = ['#f5f5f1' for _ in range(10)]
# color_map[0] = color_map[1] = color_map[2] =  '#b20710' # color highlight

# fig, ax = plt.subplots(1,1, figsize=(12, 6))
# ax.bar(data.index, data, width=0.5,
#        edgecolor='darkgray',
#        linewidth=0.6,color=color_map)

# #annotations
# for i in data.index:
#     ax.annotate(f"{data[i]}",
#                    xy=(i, data[i] + 150), #i like to change this to roughly 5% of the highest cat
#                    va = 'center', ha='center',fontweight='light', fontfamily='serif')


# # Remove border from plot

# for s in ['top', 'left', 'right']:
#     ax.spines[s].set_visible(False)

# # Tick labels

# ax.set_xticklabels(data.index, fontfamily='serif', rotation=0)

# # Title and sub-title

# fig.text(0.09, 1, 'Top 10 countries on Netflix', fontsize=15, fontweight='bold', fontfamily='serif')
# fig.text(0.09, 0.95, 'The three most frequent countries have been highlighted.', fontsize=12, fontweight='light', fontfamily='serif')

# fig.text(1.1, 1.01, 'Insight', fontsize=15, fontweight='bold', fontfamily='serif')

# fig.text(1.1, 0.67, '''
# The most prolific producers of
# content for Netflix are, primarily,
# the USA, with India and the UK
# a significant distance behind.

# It makes sense that the USA produces
# the most content as, afterall,
# Netflix is a US company.
# '''
#          , fontsize=12, fontweight='light', fontfamily='serif')

# ax.grid(axis='y', linestyle='-', alpha=0.4)

# grid_y_ticks = np.arange(0, 4000, 500) # y ticks, min, max, then step
# ax.set_yticks(grid_y_ticks)
# ax.set_axisbelow(True)

# #Axis labels

# #plt.xlabel("Country", fontsize=12, fontweight='light', fontfamily='serif',loc='left',y=-1.5)
# #plt.ylabel("Count", fontsize=12, fontweight='light', fontfamily='serif')
#  #plt.legend(loc='upper right')

# # thicken the bottom line if you want to
# plt.axhline(y = 0, color = 'black', linewidth = 1.3, alpha = .7)

# ax.tick_params(axis='both', which='major', labelsize=12)


# import matplotlib.lines as lines
# l1 = lines.Line2D([1, 1], [0, 1], transform=fig.transFigure, figure=fig,color='black',lw=0.2)
# fig.lines.extend([l1])

# ax.tick_params(axis=u'both', which=u'both',length=0)

# plt.show()

CPU times: user 13.2 ms, sys: 178 µs, total: 13.3 ms
Wall time: 11.7 ms

In [ ]:
%%time
## Transfer_post 10 ##
pd_data = data

As predicted, the USA dominates. 

The UK is a top contender too, but still some way behind India.

How does content by country vary?

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df["first_country"] = df["first_country"]

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df["type"] = df["type"]

In [18]:
%%time
### cell 11 ###

country_order = df["first_country"].value_counts()[:11].index
### STEFANOS: I didn't find a way to run the original with Modin. We're converting to Pandas and then
### back to Modin.
### ORIGINAL:
# data_q2q3 = df[['type', 'first_country']].groupby('first_country')['type'].value_counts().unstack().loc[country_order]
### MODIFIED:
if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    df = df._to_pandas()

data_q2q3 = (
    df[["type", "first_country"]]
    .groupby("first_country")["type"]
    .value_counts()
    .unstack()
    .loc[country_order]
)
if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    df = pd.DataFrame(df)
    data_q2q3 = pd.DataFrame(data_q2q3)

data_q2q3["sum"] = data_q2q3.sum(axis=1)
data_q2q3_ratio = (
    (data_q2q3.T / data_q2q3["sum"])
    .T[["Movie", "TV Show"]]
    .sort_values(by="Movie", ascending=False)[::-1]
)


# STEFANOS: Disable plotting

# ###
# fig, ax = plt.subplots(1,1,figsize=(15, 8),)

# ax.barh(data_q2q3_ratio.index, data_q2q3_ratio['Movie'],
#         color='#b20710', alpha=0.8, label='Movie')
# ax.barh(data_q2q3_ratio.index, data_q2q3_ratio['TV Show'], left=data_q2q3_ratio['Movie'],
#         color='#221f1f', alpha=0.8, label='TV Show')


# ax.set_xlim(0, 1)
# ax.set_xticks([])
# ax.set_yticklabels(data_q2q3_ratio.index, fontfamily='serif', fontsize=11)

# # male percentage
# for i in data_q2q3_ratio.index:
#     ax.annotate(f"{data_q2q3_ratio['Movie'][i]*100:.3}%",
#                    xy=(data_q2q3_ratio['Movie'][i]/2, i),
#                    va = 'center', ha='center',fontsize=12, fontweight='light', fontfamily='serif',
#                    color='white')

# for i in data_q2q3_ratio.index:
#     ax.annotate(f"{data_q2q3_ratio['TV Show'][i]*100:.3}%",
#                    xy=(data_q2q3_ratio['Movie'][i]+data_q2q3_ratio['TV Show'][i]/2, i),
#                    va = 'center', ha='center',fontsize=12, fontweight='light', fontfamily='serif',
#                    color='white')


# fig.text(0.13, 0.93, 'Top 10 countries Movie & TV Show split', fontsize=15, fontweight='bold', fontfamily='serif')
# fig.text(0.131, 0.89, 'Percent Stacked Bar Chart', fontsize=12,fontfamily='serif')

# for s in ['top', 'left', 'right', 'bottom']:
#     ax.spines[s].set_visible(False)

# #ax.legend(loc='lower center', ncol=3, bbox_to_anchor=(0.5, -0.06))

# fig.text(0.75,0.9,"Movie", fontweight="bold", fontfamily='serif', fontsize=15, color='#b20710')
# fig.text(0.81,0.9,"|", fontweight="bold", fontfamily='serif', fontsize=15, color='black')
# fig.text(0.82,0.9,"TV Show", fontweight="bold", fontfamily='serif', fontsize=15, color='#221f1f')


# fig.text(1.1, 0.93, 'Insight', fontsize=15, fontweight='bold', fontfamily='serif')

# fig.text(1.1, 0.44, '''
# Interestingly, Netflix in India
# is made up nearly entirely of Movies.

# Bollywood is big business, and perhaps
# the main focus of this industry is Movies
# and not TV Shows.

# South Korean Netflix on the other hand is
# almost entirely TV Shows.

# The underlying resons for the difference
# in content must be due to market research
# conducted by Netflix.
# '''
#          , fontsize=12, fontweight='light', fontfamily='serif')


# import matplotlib.lines as lines
# l1 = lines.Line2D([1, 1], [0, 1], transform=fig.transFigure, figure=fig,color='black',lw=0.2)
# fig.lines.extend([l1])


# ax.tick_params(axis='both', which='major', labelsize=12)
# ax.tick_params(axis=u'both', which=u'both',length=0)

# plt.show()

CPU times: user 912 ms, sys: 237 ms, total: 1.15 s
Wall time: 1.14 s

As I've noted in the insights on the plot, it is really interesting to see how the split of TV Shows and Movies varies by country.

South Korea is dominated by TV Shows - why is this? I am a huge fan of South Korean cinema so I know they have a great movie selection.

Equally, India is dominated by Movies. I think this might be due to Bollywood - comment below if you have any other ideas!

# Ratings

Let's briefly check out how ratings are distributed

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 12 ##
pd_df["rating"] = df["rating"]

In [ ]:
%%time
## Transfer_pre 12 ##
pd_df["count"] = df["count"]

In [19]:
%%time
### cell 12 ###

order = pd.DataFrame(
    df.groupby("rating")["count"].sum().sort_values(ascending=False).reset_index()
)
rating_order = list(order["rating"])

CPU times: user 15.1 ms, sys: 500 µs, total: 15.6 ms
Wall time: 13.6 ms

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 13 ##
pd_df["rating"] = df["rating"]

In [ ]:
%%time
## Transfer_pre 13 ##
pd_df["type"] = df["type"]

In [20]:
%%time
### cell 13 ###

### STEFANOS: I didn't find a way to run the original with Modin. We're converting to Pandas and then
### back to Modin.
### ORIGINAL:
# mf = df.groupby('type')['rating'].value_counts().unstack().sort_index().fillna(0).astype(int)[rating_order]
### MODIFIED:

if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    df = df._to_pandas()

mf = (
    df.groupby("type")["rating"]
    .value_counts()
    .unstack()
    .sort_index()
    .fillna(0)
    .astype(int)[rating_order]
)
if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    df = pd.DataFrame(df)
    mf = pd.DataFrame(mf)

movie = mf.loc["Movie"]
tv = -mf.loc["TV Show"]

# STEFANOS: Disable plotting

# fig, ax = plt.subplots(1,1, figsize=(12, 6))
# ax.bar(movie.index, movie, width=0.5, color='#b20710', alpha=0.8, label='Movie')
# ax.bar(tv.index, tv, width=0.5, color='#221f1f', alpha=0.8, label='TV Show')
# #ax.set_ylim(-35, 50)

# # Annotations
# for i in tv.index:
#     ax.annotate(f"{-tv[i]}",
#                    xy=(i, tv[i] - 60),
#                    va = 'center', ha='center',fontweight='light', fontfamily='serif',
#                    color='#4a4a4a')

# for i in movie.index:
#     ax.annotate(f"{movie[i]}",
#                    xy=(i, movie[i] + 60),
#                    va = 'center', ha='center',fontweight='light', fontfamily='serif',
#                    color='#4a4a4a')


# for s in ['top', 'left', 'right', 'bottom']:
#     ax.spines[s].set_visible(False)

# ax.set_xticklabels(mf.columns, fontfamily='serif')
# ax.set_yticks([])

# ax.legend().set_visible(False)
# fig.text(0.16, 1, 'Rating distribution by Film & TV Show', fontsize=15, fontweight='bold', fontfamily='serif')
# fig.text(0.16, 0.89,
# '''We observe that some ratings are only applicable to Movies.
# The most common for both Movies & TV Shows are TV-MA and TV-14.
# '''

# , fontsize=12, fontweight='light', fontfamily='serif')


# fig.text(0.755,0.924,"Movie", fontweight="bold", fontfamily='serif', fontsize=15, color='#b20710')
# fig.text(0.815,0.924,"|", fontweight="bold", fontfamily='serif', fontsize=15, color='black')
# fig.text(0.825,0.924,"TV Show", fontweight="bold", fontfamily='serif', fontsize=15, color='#221f1f')

# plt.show()

CPU times: user 24.2 s, sys: 2.67 s, total: 26.9 s
Wall time: 26.8 s

# How has content been added over the years?

As we saw in the timeline at the start of this analysis, Netflix went global in 2016 - and it is extremely noticeable in this plot.

The increase is Movie content is remarkable.

In [21]:
# STEFANOS: Disable plotting

# fig, ax = plt.subplots(1, 1, figsize=(12, 6))
# color = ["#b20710", "#221f1f"]

# for i, mtv in enumerate(df['type'].value_counts().index):
#     mtv_rel = df[df['type']==mtv]['year_added'].value_counts().sort_index()
#     ax.plot(mtv_rel.index, mtv_rel, color=color[i], label=mtv)
#     ax.fill_between(mtv_rel.index, 0, mtv_rel, color=color[i], alpha=0.9)

# ax.yaxis.tick_right()

# ax.axhline(y = 0, color = 'black', linewidth = 1.3, alpha = .7)

# #ax.set_ylim(0, 50)
# #ax.legend(loc='upper left')
# for s in ['top', 'right','bottom','left']:
#     ax.spines[s].set_visible(False)

# ax.grid(False)

# ax.set_xlim(2008,2020)
# plt.xticks(np.arange(2008, 2021, 1))

# fig.text(0.13, 0.85, 'Movies & TV Shows added over time', fontsize=15, fontweight='bold', fontfamily='serif')
# fig.text(0.13, 0.59,
# '''We see a slow start for Netflix over several years.
# Things begin to pick up in 2015 and then there is a
# rapid increase from 2016.

# It looks like content additions have slowed down in 2020,
# likely due to the COVID-19 pandemic.
# '''

# , fontsize=12, fontweight='light', fontfamily='serif')


# fig.text(0.13,0.2,"Movie", fontweight="bold", fontfamily='serif', fontsize=15, color='#b20710')
# fig.text(0.19,0.2,"|", fontweight="bold", fontfamily='serif', fontsize=15, color='black')
# fig.text(0.2,0.2,"TV Show", fontweight="bold", fontfamily='serif', fontsize=15, color='#221f1f')

# ax.tick_params(axis=u'both', which=u'both',length=0)

# plt.show()

# We can view the same plot, but as a cumulative total...

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 14 ##
pd_df["year_added"] = df["year_added"]

In [ ]:
%%time
## Transfer_pre 14 ##
pd_df["type"] = df["type"]

In [22]:
%%time
### cell 14 ###

### STEFANOS: I didn't find a way to run the original with Modin. We're converting to Pandas and then
### back to Modin.
### ORIGINAL:
# data_sub = df.groupby('type')['year_added'].value_counts().unstack().fillna(0).loc[['TV Show','Movie']].cumsum(axis=0).T
### MODIFIED:

if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    df = df._to_pandas()

data_sub = (
    df.groupby("type")["year_added"]
    .value_counts()
    .unstack()
    .fillna(0)
    .loc[["TV Show", "Movie"]]
    .cumsum(axis=0)
    .T
)
if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    df = pd.DataFrame(df)
    data_sub = pd.DataFrame(data_sub)

# STEFANOS: Disable plotting

# fig, ax = plt.subplots(1, 1, figsize=(12, 6))
# color = ["#b20710", "#221f1f"]

# for i, mtv in enumerate(df['type'].value_counts().index):
#     mtv_rel = data_sub[mtv]
#     ax.fill_between(mtv_rel.index, 0, mtv_rel, color=color[i], label=mtv,alpha=0.9)


# ax.yaxis.tick_right()

# ax.axhline(y = 0, color = 'black', linewidth = 1.3, alpha = .7)

# #ax.set_ylim(0, 50)
# #ax.legend(loc='upper left')
# for s in ['top', 'right','bottom','left']:
#     ax.spines[s].set_visible(False)

# ax.grid(False)

# ax.set_xlim(2008,2020)
# plt.xticks(np.arange(2008, 2021, 1))

# fig.text(0.13, 0.85, 'Movies & TV Shows added over time [Cumulative Total]', fontsize=15, fontweight='bold', fontfamily='serif')
# fig.text(0.13, 0.58,
# '''Netflix peak global content amount was in 2019.

# It appears that Netflix has focused more attention
# on increasing Movie content that TV Shows.
# Movies have increased much more dramatically
# than TV shows.
# '''

# , fontsize=12, fontweight='light', fontfamily='serif')


# fig.text(0.13,0.2,"Movie", fontweight="bold", fontfamily='serif', fontsize=15, color='#b20710')
# fig.text(0.19,0.2,"|", fontweight="bold", fontfamily='serif', fontsize=15, color='black')
# fig.text(0.2,0.2,"TV Show", fontweight="bold", fontfamily='serif', fontsize=15, color='#221f1f')

# ax.tick_params(axis=u'both', which=u'both',length=0)


# plt.show()

CPU times: user 43 s, sys: 3.91 s, total: 46.9 s
Wall time: 46.8 s

In [ ]:
pd_data_sub = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 14 ##
pd_data_sub["TV Show"] = data_sub["TV Show"]

In [ ]:
%%time
## Transfer_post 14 ##
pd_data_sub["Movie"] = data_sub["Movie"]

# Month-by-Month

We've seen how content has increased over the years, but are there certain months that, on average, tend to enjoy more content being added?

I'll show this in a couple of ways - a cumulative year view, and also as a radial plot...

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 15 ##
pd_df["year_added"] = df["year_added"]

In [ ]:
%%time
## Transfer_pre 15 ##
pd_df["first_country"] = df["first_country"]

In [ ]:
%%time
## Transfer_pre 15 ##
pd_df["index"] = df["index"]

In [ ]:
%%time
## Transfer_pre 15 ##
pd_df["type"] = df["type"]

In [23]:
%%time
### cell 15 ###

month_order = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
]

df["index"] = pd.Categorical(df["index"], categories=month_order, ordered=True)

CPU times: user 44 s, sys: 3.91 s, total: 47.9 s
Wall time: 47.7 s

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 15 ##
pd_df["index"] = df["index"]

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 16 ##
pd_df["type"] = df["type"]

In [ ]:
%%time
## Transfer_pre 16 ##
pd_df["index"] = df["index"]

In [ ]:
pd_data_sub = cudf.DataFrame().to_pandas()

In [24]:
%%time
### cell 16 ###


### STEFANOS: I didn't find a way to run the original with Modin. We're converting to Pandas and then
### back to Modin.
### ORIGINAL:
# data_sub = df.groupby('type')['index'].value_counts().unstack().fillna(0).loc[['TV Show','Movie']].cumsum(axis=0).T
### MODIFIED:

if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    df = df._to_pandas()

data_sub = (
    df.groupby("type")["index"]
    .value_counts()
    .unstack()
    .fillna(0)
    .loc[["TV Show", "Movie"]]
    .cumsum(axis=0)
    .T
)
if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    df = pd.DataFrame(df)
    data_sub = pd.DataFrame(data_sub)

# STEFANOS: Disable plotting

# fig, ax = plt.subplots(1, 1, figsize=(12, 6))
# color = ["#b20710", "#221f1f"]

# for i, mtv in enumerate(df['type'].value_counts().index):
#     mtv_rel = data_sub[mtv]
#     ax.fill_between(mtv_rel.index, 0, mtv_rel, color=color[i], label=mtv,alpha=0.9)


# ax.yaxis.tick_right()

# ax.axhline(y = 0, color = 'black', linewidth = 1.3, alpha = .4)

# #ax.set_ylim(0, 50)
# #ax.legend(loc='upper left')
# for s in ['top', 'right','bottom','left']:
#     ax.spines[s].set_visible(False)

# ax.grid(False)
# ax.set_xticklabels(data_sub.index, fontfamily='serif', rotation=0)
# ax.margins(x=0) # remove white spaces next to margins

# #ax.set_xlim(2008,2020)
# #plt.xticks(np.arange(2008, 2021, 1))

# fig.text(0.13, 0.95, 'Content added by month [Cumulative Total]', fontsize=15, fontweight='bold', fontfamily='serif')
# fig.text(0.13, 0.905,
# "The end & beginnings of each year seem to be Netflix's preference for adding content."

# , fontsize=12, fontweight='light', fontfamily='serif')


# fig.text(0.13,0.855,"Movie", fontweight="bold", fontfamily='serif', fontsize=15, color='#b20710')
# fig.text(0.19,0.855,"|", fontweight="bold", fontfamily='serif', fontsize=15, color='black')
# fig.text(0.2,0.855,"TV Show", fontweight="bold", fontfamily='serif', fontsize=15, color='#221f1f')


# ax.tick_params(axis=u'both', which=u'both',length=0)

# plt.show()

CPU times: user 42.8 s, sys: 3.48 s, total: 46.2 s
Wall time: 46.1 s

# What about a more interesting way to view how content is added across the year?

Sometimes visualizations should be eye-catching & attention grabbing - I think this visual acheives that, even if it isn't the most precise.

By highlighting certain months, the reader's eye is drawn exactly where we want it.

In [ ]:
pd_data_sub = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 17 ##
pd_data_sub["Movie"] = data_sub["Movie"]

In [ ]:
%%time
## Transfer_pre 17 ##
pd_data_sub["TV Show"] = data_sub["TV Show"]

In [25]:
%%time
### cell 17 ###

data_sub2 = data_sub

data_sub2["Value"] = data_sub2["Movie"] + data_sub2["TV Show"]
data_sub2 = data_sub2.reset_index()

df_polar = data_sub2.sort_values(by="index", ascending=False)


color_map = ["#221f1f" for _ in range(12)]
color_map[0] = color_map[11] = "#b20710"  # color highlight


# initialize the figure
# STEFANOS: Disable plotting
# plt.figure(figsize=(8,8))
# ax = plt.subplot(111, polar=True)
# plt.axis('off')

# Constants = parameters controling the plot layout:
upperLimit = 30
lowerLimit = 1
labelPadding = 30

# Compute max and min in the dataset
max = df_polar["Value"].max()

# Let's compute heights: they are a conversion of each item value in those new coordinates
# In our example, 0 in the dataset will be converted to the lowerLimit (10)
# The maximum will be converted to the upperLimit (100)
slope = (max - lowerLimit) / max
heights = slope * df_polar.Value + lowerLimit

# Compute the width of each bar. In total we have 2*Pi = 360°
width = 2 * np.pi / len(df_polar.index)

# Compute the angle each bar is centered on:
indexes = list(range(1, len(df_polar.index) + 1))
angles = [element * width for element in indexes]
angles

# STEFANOS: Disable plotting

# # Draw bars
# bars = ax.bar(
#     x=angles,
#     height=heights,
#     width=width,
#     bottom=lowerLimit,
#     linewidth=2,
#     edgecolor="white",
#     color=color_map,alpha=0.8
# )

# # Add labels
# for bar, angle, height, label in zip(bars,angles, heights, df_polar["index"]):

#     # Labels are rotated. Rotation must be specified in degrees :(
#     rotation = np.rad2deg(angle)

#     # Flip some labels upside down
#     alignment = ""
#     if angle >= np.pi/2 and angle < 3*np.pi/2:
#         alignment = "right"
#         rotation = rotation + 180
#     else:
#         alignment = "left"

#     # Finally add the labels
#     ax.text(
#         x=angle,
#         y=lowerLimit + bar.get_height() + labelPadding,
#         s=label,
#         ha=alignment, fontsize=10,fontfamily='serif',
#         va='center',
#         rotation=rotation,
#         rotation_mode="anchor")

CPU times: user 7.67 ms, sys: 3.97 ms, total: 11.6 ms
Wall time: 10.3 ms

[0.5235987755982988,
 1.0471975511965976,
 1.5707963267948966,
 2.0943951023931953,
 2.617993877991494,
 3.141592653589793,
 3.665191429188092,
 4.1887902047863905,
 4.71238898038469,
 5.235987755982988,
 5.759586531581287,
 6.283185307179586]

In [ ]:
pd_data_sub = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 17 ##
pd_data_sub["Value"] = data_sub["Value"]

Yes, December & January are definitely the best months for new content. Maybe Netflix knows that people have a lot of time off from work over this period and that it is a good time to reel people in?

February is the worst - why might this be? Ideas welcomed!

# Movie Genres

Let's now explore movie genres a little...

In [ ]:
%%time
## Transfer_pre 18 ##
pd_x = x

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["show_id"] = df["show_id"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["type"] = df["type"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["title"] = df["title"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["director"] = df["director"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["cast"] = df["cast"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["country"] = df["country"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["date_added"] = df["date_added"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["release_year"] = df["release_year"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["rating"] = df["rating"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["duration"] = df["duration"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["listed_in"] = df["listed_in"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["description"] = df["description"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["month_added"] = df["month_added"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["index"] = df["index"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["year_added"] = df["year_added"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["count"] = df["count"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["first_country"] = df["first_country"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["target_ages"] = df["target_ages"]

In [ ]:
%%time
## Transfer_pre 18 ##
pd_df["genre"] = df["genre"]

In [26]:
%%time
### cell 18 ###

# Genres

import matplotlib.colors


# Custom colour map based on Netflix palette
cmap = matplotlib.colors.LinearSegmentedColormap.from_list(
    "", ["#221f1f", "#b20710", "#f5f5f1"]
)


def genre_heatmap(df, title):
    df["genre"] = df["listed_in"].apply(
        lambda x: x.replace(" ,", ",").replace(", ", ",").split(",")
    )
    Types = []
    for i in df["genre"]:
        Types += i
    Types = set(Types)
    print("There are {} types in the Netflix {} Dataset".format(len(Types), title))
    test = df["genre"]


# STEFANOS: Disable ML and plotting
#     mlb = MultiLabelBinarizer()
#     res = pd.DataFrame(mlb.fit_transform(test), columns=mlb.classes_, index=test.index)
#     corr = res.corr()
#     mask = np.zeros_like(corr, dtype=np.bool)
#     mask[np.triu_indices_from(mask)] = True
#     fig, ax = plt.subplots(figsize=(10, 7))
#     fig.text(.54,.88,'Genre correlation', fontfamily='serif',fontweight='bold',fontsize=15)
#     fig.text(.75,.665,
#             '''
#              It is interesting that Independant Movies
#              tend to be Dramas.

#              Another observation is that
#              Internatinal Movies are rarely
#              in the Children's genre.
#              ''', fontfamily='serif',fontsize=12,ha='right')
#     pl = sns.heatmap(corr, mask=mask, cmap=cmap, vmax=.3, vmin=-.3, center=0, square=True, linewidths=2.5)

#     plt.show()

CPU times: user 532 µs, sys: 53 µs, total: 585 µs
Wall time: 418 µs

In [ ]:
%%time
## Transfer_pre 19 ##
pd_x = x

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 19 ##
pd_df["type"] = df["type"]

In [27]:
%%time
### cell 19 ###

df_tv = df[df["type"] == "TV Show"]
df_movies = df[df["type"] == "Movie"]


genre_heatmap(df_movies, "Movie")
# STEFANOS: Disable plotting
# plt.show()

column_view::get_data: Unsupported type: 24
column_view::get_data: Unsupported type: 24

There are 20 types in the Netflix Movie Dataset
CPU times: user 44.1 s, sys: 2.15 s, total: 46.3 s
Wall time: 46.1 s

In [ ]:
pd_df_tv = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["show_id"] = df_tv["show_id"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["type"] = df_tv["type"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["title"] = df_tv["title"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["director"] = df_tv["director"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["cast"] = df_tv["cast"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["country"] = df_tv["country"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["date_added"] = df_tv["date_added"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["release_year"] = df_tv["release_year"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["rating"] = df_tv["rating"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["duration"] = df_tv["duration"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["listed_in"] = df_tv["listed_in"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["description"] = df_tv["description"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["month_added"] = df_tv["month_added"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["index"] = df_tv["index"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["year_added"] = df_tv["year_added"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["count"] = df_tv["count"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["first_country"] = df_tv["first_country"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["target_ages"] = df_tv["target_ages"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_tv["genre"] = df_tv["genre"]

In [ ]:
pd_df_movies = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["show_id"] = df_movies["show_id"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["type"] = df_movies["type"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["title"] = df_movies["title"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["director"] = df_movies["director"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["cast"] = df_movies["cast"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["country"] = df_movies["country"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["date_added"] = df_movies["date_added"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["release_year"] = df_movies["release_year"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["rating"] = df_movies["rating"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["duration"] = df_movies["duration"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["listed_in"] = df_movies["listed_in"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["description"] = df_movies["description"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["month_added"] = df_movies["month_added"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["index"] = df_movies["index"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["year_added"] = df_movies["year_added"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["count"] = df_movies["count"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["first_country"] = df_movies["first_country"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["target_ages"] = df_movies["target_ages"]

In [ ]:
%%time
## Transfer_post 19 ##
pd_df_movies["genre"] = df_movies["genre"]

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 20 ##
pd_df["first_country"] = df["first_country"]

In [ ]:
%%time
## Transfer_pre 20 ##
pd_data = data

In [28]:
%%time
### cell 20 ###


data = (
    df.groupby("first_country")[["count"]]
    .sum()
    .sort_values(by="count", ascending=False)
    .reset_index()[:10]
)
data = data["first_country"]


df_heatmap = df.loc[df["first_country"].isin(data)]

column_view::get_data: Unsupported type: 24
CPU times: user 286 ms, sys: 64.1 ms, total: 350 ms
Wall time: 341 ms

In [ ]:
pd_df_heatmap = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["show_id"] = df_heatmap["show_id"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["type"] = df_heatmap["type"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["title"] = df_heatmap["title"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["director"] = df_heatmap["director"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["cast"] = df_heatmap["cast"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["country"] = df_heatmap["country"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["date_added"] = df_heatmap["date_added"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["release_year"] = df_heatmap["release_year"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["rating"] = df_heatmap["rating"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["duration"] = df_heatmap["duration"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["listed_in"] = df_heatmap["listed_in"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["description"] = df_heatmap["description"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["month_added"] = df_heatmap["month_added"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["index"] = df_heatmap["index"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["year_added"] = df_heatmap["year_added"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["count"] = df_heatmap["count"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["first_country"] = df_heatmap["first_country"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["target_ages"] = df_heatmap["target_ages"]

In [ ]:
%%time
## Transfer_post 20 ##
pd_df_heatmap["genre"] = df_heatmap["genre"]

In [ ]:
pd_df_heatmap = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["count"] = df_heatmap["count"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["title"] = df_heatmap["title"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["description"] = df_heatmap["description"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["release_year"] = df_heatmap["release_year"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["duration"] = df_heatmap["duration"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["month_added"] = df_heatmap["month_added"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["type"] = df_heatmap["type"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["year_added"] = df_heatmap["year_added"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["index"] = df_heatmap["index"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["listed_in"] = df_heatmap["listed_in"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["director"] = df_heatmap["director"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["show_id"] = df_heatmap["show_id"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["first_country"] = df_heatmap["first_country"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["cast"] = df_heatmap["cast"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["date_added"] = df_heatmap["date_added"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["rating"] = df_heatmap["rating"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["country"] = df_heatmap["country"]

In [ ]:
%%time
## Transfer_pre 21 ##
pd_df_heatmap["genre"] = df_heatmap["genre"]

In [29]:
%%time
### cell 21 ###

df_heatmap = pd.crosstab(
    df_heatmap["first_country"], df_heatmap["target_ages"], normalize="index"
).T

CPU times: user 850 ms, sys: 152 ms, total: 1 s
Wall time: 1 s

# Target Ages

Does Netflix uniformly target certain demographics? Or does this vary by country?

In [30]:
# STEFANOS: Disable plotting

# fig, ax = plt.subplots(1, 1, figsize=(12, 12))

# country_order2 = ['USA', 'India', 'UK', 'Canada', 'Japan', 'France', 'S. Korea', 'Spain',
#        'Mexico', 'Turkey']

# age_order = ['Kids','Older Kids','Teens','Adults']

# sns.heatmap(df_heatmap.loc[age_order,country_order2],cmap=cmap,square=True, linewidth=2.5,cbar=False,
#             annot=True,fmt='1.0%',vmax=.6,vmin=0.05,ax=ax,annot_kws={"fontsize":12})

# ax.spines['top'].set_visible(True)


# fig.text(.99, .725, 'Target ages proportion of total content by country', fontweight='bold', fontfamily='serif', fontsize=15,ha='right')
# fig.text(0.99, 0.7, 'Here we see interesting differences between countries. Most shows in India are targeted to teens, for instance.',ha='right', fontsize=12,fontfamily='serif')

# ax.set_yticklabels(ax.get_yticklabels(), fontfamily='serif', rotation = 0, fontsize=11)
# ax.set_xticklabels(ax.get_xticklabels(), fontfamily='serif', rotation=90, fontsize=11)

# ax.set_ylabel('')
# ax.set_xlabel('')
# ax.tick_params(axis=u'both', which=u'both',length=0)
# plt.tight_layout()
# plt.show()

Very interesting results. 

It is also interesting to note similarities between culturally similar countries - the US & UK are closey aligned with their Netflix target ages, yet vastly different to say, India or Japan!

# Let's have a quick look at the lag between when content is released and when it is added on Netflix

Spain looks to have a lot of new content. Great for them!

In [ ]:
pd_df_tv = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["show_id"] = df_tv["show_id"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["type"] = df_tv["type"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["title"] = df_tv["title"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["director"] = df_tv["director"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["cast"] = df_tv["cast"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["country"] = df_tv["country"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["date_added"] = df_tv["date_added"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["release_year"] = df_tv["release_year"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["rating"] = df_tv["rating"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["duration"] = df_tv["duration"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["listed_in"] = df_tv["listed_in"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["description"] = df_tv["description"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["month_added"] = df_tv["month_added"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["index"] = df_tv["index"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["year_added"] = df_tv["year_added"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["count"] = df_tv["count"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["first_country"] = df_tv["first_country"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["target_ages"] = df_tv["target_ages"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_tv["genre"] = df_tv["genre"]

In [ ]:
%%time
## Transfer_pre 22 ##
pd_data = data

In [ ]:
pd_df_movies = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 22 ##
pd_df_movies["first_country"] = df_movies["first_country"]

In [31]:
%%time
### cell 22 ###

# Data

df_movies
df_tv

### Relevant groupings

data = (
    df_movies.groupby("first_country")[["count"]]
    .sum()
    .sort_values(by="count", ascending=False)
    .reset_index()[:10]
)
data = data["first_country"]
df_loli = df_movies.loc[df_movies["first_country"].isin(data)]

loli = df_loli.groupby("first_country")[["release_year", "year_added"]].mean().round()


# Reorder it following the values of the first value
ordered_df = loli.sort_values(by="release_year")

ordered_df_rev = loli.sort_values(by="release_year", ascending=False)

# STEFANOS: Disable plotting
# my_range=range(1,len(loli.index)+1)


# fig, ax = plt.subplots(1, 1, figsize=(7, 5))

# fig.text(0.13, 0.9, 'How old are the movies? [Average]', fontsize=15, fontweight='bold', fontfamily='serif')
# plt.hlines(y=my_range, xmin=ordered_df['release_year'], xmax=ordered_df['year_added'], color='grey', alpha=0.4)
# plt.scatter(ordered_df['release_year'], my_range, color='#221f1f',s=100, alpha=0.9, label='Average release date')
# plt.scatter(ordered_df['year_added'], my_range, color='#b20710',s=100, alpha=0.9 , label='Average added date')
# #plt.legend()

# for s in ['top', 'left', 'right', 'bottom']:
#     ax.spines[s].set_visible(False)


# # Removes the tick marks but keeps the labels
# ax.tick_params(axis=u'both', which=u'both',length=0)
# # Move Y axis to the right side
# ax.yaxis.tick_right()

# plt.yticks(my_range, ordered_df.index)
# plt.yticks(fontname = "serif",fontsize=12)

# # Custome legend
# fig.text(0.19,0.175,"Released", fontweight="bold", fontfamily='serif', fontsize=12, color='#221f1f')
# fig.text(0.76,0.175,"Added", fontweight="bold", fontfamily='serif', fontsize=12, color='#b20710')


# fig.text(0.13, 0.46,
# '''The average gap between when
# content is released, and when it
# is then added on Netflix varies
# by country.

# In Spain, Netflix appears to be
# dominated by newer movies
# whereas Egypt & India have
# an older average movie.
# '''

# , fontsize=12, fontweight='light', fontfamily='serif')


# #plt.xlabel('Year')
# #plt.ylabel('Country')
# plt.show()

CPU times: user 43.9 ms, sys: 24 ms, total: 68 ms
Wall time: 60.1 ms

In [ ]:
pd_loli = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 22 ##
pd_loli["release_year"] = loli["release_year"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_loli["year_added"] = loli["year_added"]

In [ ]:
pd_df_loli = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["show_id"] = df_loli["show_id"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["type"] = df_loli["type"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["title"] = df_loli["title"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["director"] = df_loli["director"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["cast"] = df_loli["cast"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["country"] = df_loli["country"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["date_added"] = df_loli["date_added"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["release_year"] = df_loli["release_year"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["rating"] = df_loli["rating"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["duration"] = df_loli["duration"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["listed_in"] = df_loli["listed_in"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["description"] = df_loli["description"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["month_added"] = df_loli["month_added"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["index"] = df_loli["index"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["year_added"] = df_loli["year_added"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["count"] = df_loli["count"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["first_country"] = df_loli["first_country"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["target_ages"] = df_loli["target_ages"]

In [ ]:
%%time
## Transfer_post 22 ##
pd_df_loli["genre"] = df_loli["genre"]

What about TV shows...

In [ ]:
%%time
## Transfer_pre 23 ##
pd_data = data

In [ ]:
pd_df_tv = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_tv["first_country"] = df_tv["first_country"]

In [ ]:
pd_ordered_df_rev = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 23 ##
pd_ordered_df_rev["year_added"] = ordered_df_rev["year_added"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_ordered_df_rev["release_year"] = ordered_df_rev["release_year"]

In [ ]:
pd_loli = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 23 ##
pd_loli["year_added"] = loli["year_added"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_loli["release_year"] = loli["release_year"]

In [ ]:
pd_df_loli = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["count"] = df_loli["count"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["title"] = df_loli["title"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["description"] = df_loli["description"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["release_year"] = df_loli["release_year"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["duration"] = df_loli["duration"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["month_added"] = df_loli["month_added"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["type"] = df_loli["type"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["year_added"] = df_loli["year_added"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["index"] = df_loli["index"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["listed_in"] = df_loli["listed_in"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["director"] = df_loli["director"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["show_id"] = df_loli["show_id"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["first_country"] = df_loli["first_country"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["cast"] = df_loli["cast"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["date_added"] = df_loli["date_added"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["rating"] = df_loli["rating"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["country"] = df_loli["country"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_df_loli["genre"] = df_loli["genre"]

In [ ]:
pd_ordered_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 23 ##
pd_ordered_df["year_added"] = ordered_df["year_added"]

In [ ]:
%%time
## Transfer_pre 23 ##
pd_ordered_df["release_year"] = ordered_df["release_year"]

In [32]:
%%time
### cell 23 ###

data = (
    df_tv.groupby("first_country")[["count"]]
    .sum()
    .sort_values(by="count", ascending=False)
    .reset_index()[:10]
)
data = data["first_country"]
df_loli = df_tv.loc[df_tv["first_country"].isin(data)]

loli = df_loli.groupby("first_country")[["release_year", "year_added"]].mean().round()


# Reorder it following the values of the first value:
ordered_df = loli.sort_values(by="release_year")

ordered_df_rev = loli.sort_values(by="release_year", ascending=False)

# STEFANOS: Disable plotting


# my_range=range(1,len(loli.index)+1)


# fig, ax = plt.subplots(1, 1, figsize=(7, 5))

# fig.text(0.13, 0.9, 'How old are the TV shows? [Average]', fontsize=15, fontweight='bold', fontfamily='serif')
# plt.hlines(y=my_range, xmin=ordered_df['release_year'], xmax=ordered_df['year_added'], color='grey', alpha=0.4)
# plt.scatter(ordered_df['release_year'], my_range, color='#221f1f',s=100, alpha=0.9, label='Average release date')
# plt.scatter(ordered_df['year_added'], my_range, color='#b20710',s=100, alpha=0.9 , label='Average added date')
# #plt.legend()

# for s in ['top', 'left', 'right', 'bottom']:
#     ax.spines[s].set_visible(False)

# ax.yaxis.tick_right()
# plt.yticks(my_range, ordered_df.index)
# plt.yticks(fontname = "serif",fontsize=12)


# fig.text(0.19,0.175,"Released", fontweight="bold", fontfamily='serif', fontsize=12, color='#221f1f')

# fig.text(0.47,0.175,"Added", fontweight="bold", fontfamily='serif', fontsize=12, color='#b20710')


# fig.text(0.13, 0.42,
# '''The gap for TV shows seems
# more regular than for movies.

# This is likely due to subsequent
# series being released
# year-on-year.

# Spain seems to have
# the newest content
# overall.
# '''

# , fontsize=12, fontweight='light', fontfamily='serif')


# ax.tick_params(axis=u'both', which=u'both',length=0)
# #plt.xlabel('Value of the variables')
# #plt.ylabel('Group')
# plt.show()

column_view::get_data: Unsupported type: 24
CPU times: user 37.8 ms, sys: 12.9 ms, total: 50.6 ms
Wall time: 43.6 ms

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 24 ##
pd_df["year_added"] = df["year_added"]

In [ ]:
%%time
## Transfer_pre 24 ##
pd_df["first_country"] = df["first_country"]

In [ ]:
pd_data_sub = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 24 ##
pd_data_sub["Value"] = data_sub["Value"]

In [33]:
%%time
### cell 24 ###


us_ind = df[(df["first_country"] == "USA") | (df["first_country"] == "India")]


### STEFANOS: I didn't find a way to run the original with Modin. We're converting to Pandas and then
### back to Modin.
### ORIGINAL:
# data_sub = df.groupby('first_country')['year_added'].value_counts().unstack().fillna(0).loc[['USA','India']].cumsum(axis=0).T
### MODIFIED:

if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    df = df._to_pandas()

data_sub = (
    df.groupby("first_country")["year_added"]
    .value_counts()
    .unstack()
    .fillna(0)
    .loc[["USA", "India"]]
    .cumsum(axis=0)
    .T
)
if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    df = pd.DataFrame(df)
    data_sub = pd.DataFrame(data_sub)

column_view::get_data: Unsupported type: 24

CPU times: user 24.6 s, sys: 2.6 s, total: 27.2 s
Wall time: 27.1 s

In [ ]:
pd_us_ind = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["show_id"] = us_ind["show_id"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["type"] = us_ind["type"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["title"] = us_ind["title"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["director"] = us_ind["director"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["cast"] = us_ind["cast"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["country"] = us_ind["country"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["date_added"] = us_ind["date_added"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["release_year"] = us_ind["release_year"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["rating"] = us_ind["rating"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["duration"] = us_ind["duration"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["listed_in"] = us_ind["listed_in"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["description"] = us_ind["description"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["month_added"] = us_ind["month_added"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["index"] = us_ind["index"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["year_added"] = us_ind["year_added"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["count"] = us_ind["count"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["first_country"] = us_ind["first_country"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["target_ages"] = us_ind["target_ages"]

In [ ]:
%%time
## Transfer_post 24 ##
pd_us_ind["genre"] = us_ind["genre"]

# USA & India

As the two largest content countries, it might be fun to compare the two

In [34]:
# STEFANOS: Disable plotting

# fig, ax = plt.subplots(1, 1, figsize=(12, 6))
# color = ['#221f1f', '#b20710','#f5f5f1']

# for i, hs in enumerate(us_ind['first_country'].value_counts().index):
#     hs_built = us_ind[us_ind['first_country']==hs]['year_added'].value_counts().sort_index()
#     ax.plot(hs_built.index, hs_built, color=color[i], label=hs)
#     #ax.fill_between(hs_built.index, 0, hs_built, color=color[i], alpha=0.4)
#     ax.fill_between(hs_built.index, 0, hs_built, color=color[i], label=hs)


# ax.set_ylim(0, 1000)
# #ax.legend(loc='upper left')
# for s in ['top', 'right']:
#     ax.spines[s].set_visible(False)

# ax.yaxis.tick_right()

# ax.axhline(y = 0, color = 'black', linewidth = 1.3, alpha = .4)

# #ax.set_ylim(0, 50)
# #ax.legend(loc='upper left')
# for s in ['top', 'right','bottom','left']:
#     ax.spines[s].set_visible(False)

# ax.grid(False)
# ax.set_xticklabels(data_sub.index, fontfamily='serif', rotation=0)
# ax.margins(x=0) # remove white spaces next to margins

# ax.set_xlim(2008,2020)
# plt.xticks(np.arange(2008, 2021, 1))

# fig.text(0.13, 0.85, 'USA vs. India: When was content added?', fontsize=15, fontweight='bold', fontfamily='serif')
# fig.text(0.13, 0.58,
# '''
# We know from our work above that Netflix is dominated by the USA & India.
# It would also be reasonable to assume that, since Netflix is an American
# compnany, Netflix increased content first in the USA, before
# other nations.

# That is exactly what we see here; a slow and then rapid
# increase in content for the USA, followed by Netflix
# being launched to the Indian market in 2016.'''

# , fontsize=12, fontweight='light', fontfamily='serif')


# fig.text(0.13,0.15,"India", fontweight="bold", fontfamily='serif', fontsize=15, color='#b20710')
# fig.text(0.188,0.15,"|", fontweight="bold", fontfamily='serif', fontsize=15, color='black')
# fig.text(0.198,0.15,"USA", fontweight="bold", fontfamily='serif', fontsize=15, color='#221f1f')


# ax.tick_params(axis=u'both', which=u'both',length=0)


# plt.show()

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 25 ##
pd_df["year_added"] = df["year_added"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_df["first_country"] = df["first_country"]

In [ ]:
pd_data_sub = cudf.DataFrame().to_pandas()

In [ ]:
pd_us_ind = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["count"] = us_ind["count"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["title"] = us_ind["title"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["description"] = us_ind["description"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["release_year"] = us_ind["release_year"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["duration"] = us_ind["duration"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["month_added"] = us_ind["month_added"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["type"] = us_ind["type"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["year_added"] = us_ind["year_added"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["index"] = us_ind["index"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["listed_in"] = us_ind["listed_in"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["director"] = us_ind["director"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["show_id"] = us_ind["show_id"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["first_country"] = us_ind["first_country"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["cast"] = us_ind["cast"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["date_added"] = us_ind["date_added"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["rating"] = us_ind["rating"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["country"] = us_ind["country"]

In [ ]:
%%time
## Transfer_pre 25 ##
pd_us_ind["genre"] = us_ind["genre"]

In [35]:
%%time
### cell 25 ###

us_ind = df[(df["first_country"] == "USA") | (df["first_country"] == "India")]

### STEFANOS: I didn't find a way to run the original with Modin. We're converting to Pandas and then
### back to Modin.
### ORIGINAL:
# data_sub = df.groupby('first_country')['year_added'].value_counts().unstack().fillna(0).loc[['USA','India']].cumsum(axis=0).T
### MODIFIED:

if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    df = df._to_pandas()

data_sub = (
    df.groupby("first_country")["year_added"]
    .value_counts()
    .unstack()
    .fillna(0)
    .loc[["USA", "India"]]
    .cumsum(axis=0)
    .T
)
if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    df = pd.DataFrame(df)
    data_sub = pd.DataFrame(data_sub)


data_sub.insert(0, "base", np.zeros(len(data_sub)))

data_sub = data_sub.add(-us_ind["year_added"].value_counts() / 2, axis=0)

column_view::get_data: Unsupported type: 24

CPU times: user 43.1 s, sys: 3.73 s, total: 46.8 s
Wall time: 46.7 s

So the USA dominates. But is there a plot that can convey this in another way?

In [36]:
# STEFANOS: Disable plotting

# fig, ax = plt.subplots(1, 1, figsize=(14, 6))
# color = ['#b20710','#221f1f'][::-1]
# hs_list = data_sub.columns
# hs_built = data_sub[hs]

# for i, hs in enumerate(hs_list):
#     if i == 0 : continue
#     ax.fill_between(hs_built.index, data_sub.iloc[:,i-1], data_sub.iloc[:,i], color=color[i-1])

# for s in ['top', 'right', 'bottom', 'left']:
#     ax.spines[s].set_visible(False)
# ax.set_axisbelow(True)
# ax.set_yticks([])
# #ax.legend(loc='upper left')
# ax.grid(False)

# fig.text(0.16, 0.76, 'USA vs. India: Stream graph of new content added', fontsize=15, fontweight='bold', fontfamily='serif')
# fig.text(0.16, 0.575,
# '''
# Seeing the data displayed like this helps
# us to realise just how much content is added in the USA.
# Remember, India has the second largest amount of
# content yet is dwarfed by the USA.'''

# , fontsize=12, fontweight='light', fontfamily='serif')

# fig.text(0.16,0.41,"India", fontweight="bold", fontfamily='serif', fontsize=15, color='#b20710')
# fig.text(0.208,0.41,"|", fontweight="bold", fontfamily='serif', fontsize=15, color='black')
# fig.text(0.218,0.41,"USA", fontweight="bold", fontfamily='serif', fontsize=15, color='#221f1f')


# ax.tick_params(axis=u'y', which=u'both',length=0)

# plt.show()

# Lastly, we can view a wordcloud to get an overview of Netflix titles


It is interesting to note that many films share the same key words in their titles.



Credit to Dmitry Uarov for figuring this visual out. His notebook is here:

https://www.kaggle.com/dmitryuarov/netflix-eda-with-plotly

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 26 ##
pd_df["title"] = df["title"]

In [37]:
%%time
### cell 26 ###

# STEFANOS: Uneeded
# from wordcloud import WordCloud
import matplotlib

# Custom colour map based on Netflix palette
# STEFANOS: Disable plotting
# cmap = matplotlib.colors.LinearSegmentedColormap.from_list("", ['#221f1f', '#b20710'])

text = (
    str(list(df["title"]))
    .replace(",", "")
    .replace("[", "")
    .replace("'", "")
    .replace("]", "")
    .replace(".", "")
)

# STEFANOS: Can't find the icon
# mask = np.array(Image.open('../input/netflix-icon-new/f6974e017d3f6196c4cbe284ee3eaf4e.png'))


# STEFANOS: Disable ML and plotting
# wordcloud = WordCloud(background_color = 'white', width = 500,  height = 200,colormap=cmap, max_words = 150, mask = mask).generate(text)

# plt.figure( figsize=(5,5))
# plt.imshow(wordcloud, interpolation = 'bilinear')
# plt.axis('off')
# plt.tight_layout(pad=0)
# plt.show()

CPU times: user 22.7 s, sys: 1.55 s, total: 24.2 s
Wall time: 24.2 s


# Thanks for reading!

# I hope you enjoyed my visuals 

# Please consider upvoting if you did

# Have a great day


View more of my work:

**Exploratory Data Visualization - Student Performance**

https://www.kaggle.com/joshuaswords/data-visualisation-student-results

**Visuals & Modelling**

https://www.kaggle.com/joshuaswords/awesome-hr-data-visualization-prediction

**Visuals & Customer Segmentation**

https://www.kaggle.com/joshuaswords/data-visualization-clustering-mall-data

**March 2021 Tabular Playground Series**

https://www.kaggle.com/joshuaswords/tps-eda-model-march-2020