In [1]:
%load_ext cudf.pandas

In [2]:
import sys
import os
sys.path.insert(0, os.path.abspath('/home/ElasticNotebook'))
%load_ext ElasticNotebook
import cudf

Enabled rmm statistics

# Exploratory Data Analysis

In this notebook we will look into the speedtest data gathered from ookla and draw some useful insights from the dataset. Additional dataset would also be utilized to make some meaningful insights into the appropriately combined wholistic data

## File Exploration

In the following block we see all the files available for this kernel. The relevant libraries are also imported to process the data extracted from the dataset.

In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import os
# STEFANOS: Conditionally import Modin Pandas
if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    # STEFANOS: Import Modin Pandas
    import os
    os.environ["MODIN_ENGINE"] = "ray"
    import ray
    ray.init(num_cpus=int(os.environ['MODIN_CPUS']), runtime_env={'env_vars': {'__MODIN_AUTOIMPORT_PANDAS__': '1'}})
    import modin.pandas as pd
else:
    # STEFANOS: Import regular Pandas
    import pandas as pd
import regex as re # For String searches
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/mobile_year_2020_quarter_02.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/fixed_year_2020_quarter_01.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/mobile_year_2021_quarter_01.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/mobile_year_2021_quarter_03.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/fixed_year_2020_quarter_02.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/mobile_year_2021_quarter_02.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/mobile_year_2020_quarter_03.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/mobile_year_2022_quarter_01.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/fixed_year_2020_quarter_03.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/fixed_year_2021_quarter_04.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/mobile_year_2021_quarter_04.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/fixed_year_2021_quarter_03.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/mobile_year_2020_quarter_01.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/fixed_year_2022_quarter_02.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/fixed_year_2020_quarter_04.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/fixed_year_2021_quarter_01.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/fixed_year_2022_quarter_01.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/mobile_year_2022_quarter_03.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/fixed_year_2022_quarter_03.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/mobile_year_2022_quarter_02.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/fixed_year_2021_quarter_02.csv
/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/mobile_year_2020_quarter_04.csv

In [4]:
%%time
### cell 0 ###

data = pd.read_csv('/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input/speedtest-data-by-ookla/fixed_year_2021_quarter_03.csv')
data.head()

CPU times: user 19.2 ms, sys: 68 ms, total: 87.2 ms
Wall time: 83 ms

,Name,Number of Records,Devices,Tests,Avg. Avg U Kbps,Avg. Avg D Kbps,Avg Lat Ms,Avg. Pop2005,Rank Upload,Rank Download,Rank Latency
0,Afghanistan,897,"2,312","9,003","3,983","4,823",70,"25,067,407",217,231,33
1,Åland Islands,284,580,"1,341","58,693","82,767",11,0,27,47,215
2,Albania,"7,215","38,905","104,752","17,354","25,803",20,"3,153,731",100,127,159
3,Algeria,"16,056","70,929","413,666","1,508","9,057",43,"32,854,159",234,211,68
4,American Samoa,80,202,900,"14,345","33,078",18,"64,051",119,104,171

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Name'] = data['Name']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Number of Records'] = data['Number of Records']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Devices'] = data['Devices']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Tests'] = data['Tests']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Avg. Avg U Kbps'] = data['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Avg. Avg D Kbps'] = data['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Avg Lat Ms'] = data['Avg Lat Ms']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Avg. Pop2005'] = data['Avg. Pop2005']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Rank Upload'] = data['Rank Upload']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Rank Download'] = data['Rank Download']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Rank Latency'] = data['Rank Latency']

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Name'] = data['Name']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Number of Records'] = data['Number of Records']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Devices'] = data['Devices']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Tests'] = data['Tests']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Avg. Avg U Kbps'] = data['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Avg. Avg D Kbps'] = data['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Avg Lat Ms'] = data['Avg Lat Ms']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Avg. Pop2005'] = data['Avg. Pop2005']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Rank Upload'] = data['Rank Upload']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Rank Download'] = data['Rank Download']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Rank Latency'] = data['Rank Latency']

In [5]:
%%time
### cell 1 ###

data.info()

<class 'cudf.core.dataframe.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               236 non-null    object
 1   Number of Records  236 non-null    object
 2   Devices            236 non-null    object
 3   Tests              236 non-null    object
 4   Avg. Avg U Kbps    236 non-null    object
 5   Avg. Avg D Kbps    236 non-null    object
 6   Avg Lat Ms         236 non-null    int64
 7   Avg. Pop2005       236 non-null    object
 8   Rank Upload        236 non-null    int64
 9   Rank Download      236 non-null    int64
 10  Rank Latency       236 non-null    int64
dtypes: int64(4), object(7)
memory usage: 24.3+ KB
CPU times: user 27.5 ms, sys: 0 ns, total: 27.5 ms
Wall time: 26 ms

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Name'] = data['Name']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Number of Records'] = data['Number of Records']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Devices'] = data['Devices']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Tests'] = data['Tests']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Avg. Avg U Kbps'] = data['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Avg. Avg D Kbps'] = data['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Avg Lat Ms'] = data['Avg Lat Ms']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Avg. Pop2005'] = data['Avg. Pop2005']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Rank Upload'] = data['Rank Upload']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Rank Download'] = data['Rank Download']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Rank Latency'] = data['Rank Latency']

In [6]:
%%time
### cell 2 ###

Mobile_df = pd.DataFrame([],columns=data.columns)
Broadband_df = pd.DataFrame([],columns=data.columns)

def col_name_corrections(df,correction_pair):
    if set(df.columns).intersection(set(correction_pair.keys())):
        df.rename(columns=correction_pair,inplace=True)
    return df

for dirname, _, filenames in os.walk('/home/dias-benchmarks/notebooks/gksriharsha/eda-speedtests/input'):
    for filename in filenames:
        meta_info = filename.split('/')[-1]
        data = pd.read_csv(dirname+'/'+filename,thousands=r',').convert_dtypes()
        data = col_name_corrections(data,{'Number of Record':'Number of Records'})
        data['Year'] = np.int64(re.search('year_(.*)_quarter',meta_info).group(1))
        data['Quarter'] = np.int64(re.search('quarter_(.*).csv',meta_info).group(1))
        if 'mobile' in meta_info:
            Mobile_df = pd.concat([Mobile_df,data])
        else:
            Broadband_df = pd.concat([Broadband_df,data]) 
print(Broadband_df.shape)
print(Mobile_df.shape)
Mobile_df = Mobile_df.astype({'Year':np.int64,'Quarter':np.int64})
Broadband_df = Broadband_df.astype({'Year':np.int64,'Quarter':np.int64})
Mobile_df.sort_values(by=['Year','Quarter'],ascending=[True,True],inplace=True)
Broadband_df.sort_values(by=['Year','Quarter'],ascending=[True,True],inplace=True)

(2597, 13)
(2487, 13)
CPU times: user 288 ms, sys: 55.8 ms, total: 343 ms
Wall time: 290 ms

In [ ]:
pd_Broadband_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 2 ##
pd_Broadband_df['Name'] = Broadband_df['Name']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Broadband_df['Number of Records'] = Broadband_df['Number of Records']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Broadband_df['Devices'] = Broadband_df['Devices']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Broadband_df['Tests'] = Broadband_df['Tests']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Broadband_df['Avg. Avg U Kbps'] = Broadband_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Broadband_df['Avg. Avg D Kbps'] = Broadband_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Broadband_df['Avg Lat Ms'] = Broadband_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Broadband_df['Avg. Pop2005'] = Broadband_df['Avg. Pop2005']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Broadband_df['Rank Upload'] = Broadband_df['Rank Upload']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Broadband_df['Rank Download'] = Broadband_df['Rank Download']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Broadband_df['Rank Latency'] = Broadband_df['Rank Latency']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Broadband_df['Year'] = Broadband_df['Year']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Broadband_df['Quarter'] = Broadband_df['Quarter']

In [ ]:
pd_Mobile_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 2 ##
pd_Mobile_df['Name'] = Mobile_df['Name']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Mobile_df['Number of Records'] = Mobile_df['Number of Records']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Mobile_df['Devices'] = Mobile_df['Devices']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Mobile_df['Tests'] = Mobile_df['Tests']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Mobile_df['Avg. Avg U Kbps'] = Mobile_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Mobile_df['Avg. Avg D Kbps'] = Mobile_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Mobile_df['Avg Lat Ms'] = Mobile_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Mobile_df['Avg. Pop2005'] = Mobile_df['Avg. Pop2005']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Mobile_df['Rank Upload'] = Mobile_df['Rank Upload']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Mobile_df['Rank Download'] = Mobile_df['Rank Download']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Mobile_df['Rank Latency'] = Mobile_df['Rank Latency']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Mobile_df['Year'] = Mobile_df['Year']

In [ ]:
%%time
## Transfer_post 2 ##
pd_Mobile_df['Quarter'] = Mobile_df['Quarter']

It can be seen that there are more broadband rows than Mobile rows. This is a point that should be noted each row corresponds to a country's statistics in the particular year and quarter. Missing data indicates lack of speed test data from the country.

In [ ]:
pd_Mobile_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 3 ##
pd_Mobile_df['Name'] = Mobile_df['Name']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_Mobile_df['Number of Records'] = Mobile_df['Number of Records']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_Mobile_df['Devices'] = Mobile_df['Devices']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_Mobile_df['Tests'] = Mobile_df['Tests']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_Mobile_df['Avg. Avg U Kbps'] = Mobile_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_Mobile_df['Avg. Avg D Kbps'] = Mobile_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_Mobile_df['Avg Lat Ms'] = Mobile_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_Mobile_df['Avg. Pop2005'] = Mobile_df['Avg. Pop2005']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_Mobile_df['Rank Upload'] = Mobile_df['Rank Upload']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_Mobile_df['Rank Download'] = Mobile_df['Rank Download']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_Mobile_df['Rank Latency'] = Mobile_df['Rank Latency']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_Mobile_df['Year'] = Mobile_df['Year']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_Mobile_df['Quarter'] = Mobile_df['Quarter']

In [7]:
%%time
### cell 3 ###

Mobile_df.info()

<class 'cudf.core.dataframe.DataFrame'>
Index: 2487 entries, 0 to 232
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               2487 non-null   object
 1   Number of Records  2487 non-null   int64
 2   Devices            2487 non-null   int64
 3   Tests              2487 non-null   int64
 4   Avg. Avg U Kbps    2487 non-null   int64
 5   Avg. Avg D Kbps    2487 non-null   int64
 6   Avg Lat Ms         2487 non-null   int64
 7   Avg. Pop2005       2487 non-null   int64
 8   Rank Upload        2487 non-null   int64
 9   Rank Download      2487 non-null   int64
 10  Rank Latency       2487 non-null   int64
 11  Year               2487 non-null   int64
 12  Quarter            2487 non-null   int64
dtypes: int64(12), object(1)
memory usage: 286.8+ KB
CPU times: user 18.4 ms, sys: 46 µs, total: 18.4 ms
Wall time: 16.4 ms

# -- STEFANOS -- Replicate Data

In [ ]:
pd_Mobile_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 4 ##
pd_Mobile_df['Name'] = Mobile_df['Name']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_Mobile_df['Number of Records'] = Mobile_df['Number of Records']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_Mobile_df['Devices'] = Mobile_df['Devices']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_Mobile_df['Tests'] = Mobile_df['Tests']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_Mobile_df['Avg. Avg U Kbps'] = Mobile_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_Mobile_df['Avg. Avg D Kbps'] = Mobile_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_Mobile_df['Avg Lat Ms'] = Mobile_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_Mobile_df['Avg. Pop2005'] = Mobile_df['Avg. Pop2005']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_Mobile_df['Rank Upload'] = Mobile_df['Rank Upload']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_Mobile_df['Rank Download'] = Mobile_df['Rank Download']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_Mobile_df['Rank Latency'] = Mobile_df['Rank Latency']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_Mobile_df['Year'] = Mobile_df['Year']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_Mobile_df['Quarter'] = Mobile_df['Quarter']

In [8]:
%%time
### cell 4 ###

# factor = 2000
factor = 2000
Mobile_df = pd.concat([Mobile_df]*factor, ignore_index=True)
Mobile_df.info()

<class 'cudf.core.dataframe.DataFrame'>
RangeIndex: 4974000 entries, 0 to 4973999
Data columns (total 13 columns):
 #   Column             Dtype
---  ------             -----
 0   Name               object
 1   Number of Records  int64
 2   Devices            int64
 3   Tests              int64
 4   Avg. Avg U Kbps    int64
 5   Avg. Avg D Kbps    int64
 6   Avg Lat Ms         int64
 7   Avg. Pop2005       int64
 8   Rank Upload        int64
 9   Rank Download      int64
 10  Rank Latency       int64
 11  Year               int64
 12  Quarter            int64
dtypes: int64(12), object(1)
memory usage: 522.1+ MB
CPU times: user 1.19 s, sys: 247 ms, total: 1.43 s
Wall time: 1.25 s

In [ ]:
pd_Mobile_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 4 ##
pd_Mobile_df['Name'] = Mobile_df['Name']

In [ ]:
%%time
## Transfer_post 4 ##
pd_Mobile_df['Number of Records'] = Mobile_df['Number of Records']

In [ ]:
%%time
## Transfer_post 4 ##
pd_Mobile_df['Devices'] = Mobile_df['Devices']

In [ ]:
%%time
## Transfer_post 4 ##
pd_Mobile_df['Tests'] = Mobile_df['Tests']

In [ ]:
%%time
## Transfer_post 4 ##
pd_Mobile_df['Avg. Avg U Kbps'] = Mobile_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_post 4 ##
pd_Mobile_df['Avg. Avg D Kbps'] = Mobile_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_post 4 ##
pd_Mobile_df['Avg Lat Ms'] = Mobile_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_post 4 ##
pd_Mobile_df['Avg. Pop2005'] = Mobile_df['Avg. Pop2005']

In [ ]:
%%time
## Transfer_post 4 ##
pd_Mobile_df['Rank Upload'] = Mobile_df['Rank Upload']

In [ ]:
%%time
## Transfer_post 4 ##
pd_Mobile_df['Rank Download'] = Mobile_df['Rank Download']

In [ ]:
%%time
## Transfer_post 4 ##
pd_Mobile_df['Rank Latency'] = Mobile_df['Rank Latency']

In [ ]:
%%time
## Transfer_post 4 ##
pd_Mobile_df['Year'] = Mobile_df['Year']

In [ ]:
%%time
## Transfer_post 4 ##
pd_Mobile_df['Quarter'] = Mobile_df['Quarter']

In [ ]:
pd_Broadband_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 5 ##
pd_Broadband_df['Name'] = Broadband_df['Name']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_Broadband_df['Number of Records'] = Broadband_df['Number of Records']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_Broadband_df['Devices'] = Broadband_df['Devices']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_Broadband_df['Tests'] = Broadband_df['Tests']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_Broadband_df['Avg. Avg U Kbps'] = Broadband_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_Broadband_df['Avg. Avg D Kbps'] = Broadband_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_Broadband_df['Avg Lat Ms'] = Broadband_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_Broadband_df['Avg. Pop2005'] = Broadband_df['Avg. Pop2005']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_Broadband_df['Rank Upload'] = Broadband_df['Rank Upload']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_Broadband_df['Rank Download'] = Broadband_df['Rank Download']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_Broadband_df['Rank Latency'] = Broadband_df['Rank Latency']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_Broadband_df['Year'] = Broadband_df['Year']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_Broadband_df['Quarter'] = Broadband_df['Quarter']

In [9]:
%%time
### cell 5 ###

factor = 1000
Broadband_df = pd.concat([Broadband_df]*factor, ignore_index=True)
Broadband_df.info()

<class 'cudf.core.dataframe.DataFrame'>
RangeIndex: 2597000 entries, 0 to 2596999
Data columns (total 13 columns):
 #   Column             Dtype
---  ------             -----
 0   Name               object
 1   Number of Records  int64
 2   Devices            int64
 3   Tests              int64
 4   Avg. Avg U Kbps    int64
 5   Avg. Avg D Kbps    int64
 6   Avg Lat Ms         int64
 7   Avg. Pop2005       int64
 8   Rank Upload        int64
 9   Rank Download      int64
 10  Rank Latency       int64
 11  Year               int64
 12  Quarter            int64
dtypes: int64(12), object(1)
memory usage: 273.4+ MB
CPU times: user 553 ms, sys: 102 ms, total: 655 ms
Wall time: 619 ms

In [ ]:
pd_Broadband_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 5 ##
pd_Broadband_df['Name'] = Broadband_df['Name']

In [ ]:
%%time
## Transfer_post 5 ##
pd_Broadband_df['Number of Records'] = Broadband_df['Number of Records']

In [ ]:
%%time
## Transfer_post 5 ##
pd_Broadband_df['Devices'] = Broadband_df['Devices']

In [ ]:
%%time
## Transfer_post 5 ##
pd_Broadband_df['Tests'] = Broadband_df['Tests']

In [ ]:
%%time
## Transfer_post 5 ##
pd_Broadband_df['Avg. Avg U Kbps'] = Broadband_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_post 5 ##
pd_Broadband_df['Avg. Avg D Kbps'] = Broadband_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_post 5 ##
pd_Broadband_df['Avg Lat Ms'] = Broadband_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_post 5 ##
pd_Broadband_df['Avg. Pop2005'] = Broadband_df['Avg. Pop2005']

In [ ]:
%%time
## Transfer_post 5 ##
pd_Broadband_df['Rank Upload'] = Broadband_df['Rank Upload']

In [ ]:
%%time
## Transfer_post 5 ##
pd_Broadband_df['Rank Download'] = Broadband_df['Rank Download']

In [ ]:
%%time
## Transfer_post 5 ##
pd_Broadband_df['Rank Latency'] = Broadband_df['Rank Latency']

In [ ]:
%%time
## Transfer_post 5 ##
pd_Broadband_df['Year'] = Broadband_df['Year']

In [ ]:
%%time
## Transfer_post 5 ##
pd_Broadband_df['Quarter'] = Broadband_df['Quarter']

In [ ]:
pd_Mobile_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 6 ##
pd_Mobile_df['Name'] = Mobile_df['Name']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_Mobile_df['Number of Records'] = Mobile_df['Number of Records']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_Mobile_df['Devices'] = Mobile_df['Devices']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_Mobile_df['Tests'] = Mobile_df['Tests']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_Mobile_df['Avg. Avg U Kbps'] = Mobile_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_Mobile_df['Avg. Avg D Kbps'] = Mobile_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_Mobile_df['Avg Lat Ms'] = Mobile_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_Mobile_df['Avg. Pop2005'] = Mobile_df['Avg. Pop2005']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_Mobile_df['Rank Upload'] = Mobile_df['Rank Upload']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_Mobile_df['Rank Download'] = Mobile_df['Rank Download']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_Mobile_df['Rank Latency'] = Mobile_df['Rank Latency']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_Mobile_df['Year'] = Mobile_df['Year']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_Mobile_df['Quarter'] = Mobile_df['Quarter']

In [10]:
%%time
### cell 6 ###

Mobile_df.head()

CPU times: user 796 µs, sys: 1.32 ms, total: 2.12 ms
Wall time: 1.74 ms

,Name,Number of Records,Devices,Tests,Avg. Avg U Kbps,Avg. Avg D Kbps,Avg Lat Ms,Avg. Pop2005,Rank Upload,Rank Download,Rank Latency,Year,Quarter
0,Afghanistan,789,1241,3541,3099,6387,70,25067407,220,220,32,2020,1
1,Albania,1626,4513,7228,11414,40238,26,3153731,75,42,197,2020,1
2,Algeria,14174,48699,124160,6150,7724,65,32854159,197,213,35,2020,1
3,American Samoa,23,33,63,8488,22792,62,64051,156,111,38,2020,1
4,Andorra,45,83,110,18160,72764,39,73483,9,6,112,2020,1

In [ ]:
pd_Broadband_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 7 ##
pd_Broadband_df['Name'] = Broadband_df['Name']

In [11]:
%%time
### cell 7 ###

unique_countries_broadband = Broadband_df.groupby('Name').count()
unique_countries_broadband.head()

CPU times: user 28.8 ms, sys: 40.4 ms, total: 69.2 ms
Wall time: 62.4 ms

,Number of Records,Devices,Tests,Avg. Avg U Kbps,Avg. Avg D Kbps,Avg Lat Ms,Avg. Pop2005,Rank Upload,Rank Download,Rank Latency,Year,Quarter
Name,,,,,,,,,,,,
Afghanistan,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000
Albania,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000
Algeria,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000
American Samoa,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000
Andorra,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000,11000

In [ ]:
pd_unique_countries_broadband = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 7 ##
pd_unique_countries_broadband['Number of Records'] = unique_countries_broadband['Number of Records']

In [ ]:
%%time
## Transfer_post 7 ##
pd_unique_countries_broadband['Devices'] = unique_countries_broadband['Devices']

In [ ]:
%%time
## Transfer_post 7 ##
pd_unique_countries_broadband['Tests'] = unique_countries_broadband['Tests']

In [ ]:
%%time
## Transfer_post 7 ##
pd_unique_countries_broadband['Avg. Avg U Kbps'] = unique_countries_broadband['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_post 7 ##
pd_unique_countries_broadband['Avg. Avg D Kbps'] = unique_countries_broadband['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_post 7 ##
pd_unique_countries_broadband['Avg Lat Ms'] = unique_countries_broadband['Avg Lat Ms']

In [ ]:
%%time
## Transfer_post 7 ##
pd_unique_countries_broadband['Avg. Pop2005'] = unique_countries_broadband['Avg. Pop2005']

In [ ]:
%%time
## Transfer_post 7 ##
pd_unique_countries_broadband['Rank Upload'] = unique_countries_broadband['Rank Upload']

In [ ]:
%%time
## Transfer_post 7 ##
pd_unique_countries_broadband['Rank Download'] = unique_countries_broadband['Rank Download']

In [ ]:
%%time
## Transfer_post 7 ##
pd_unique_countries_broadband['Rank Latency'] = unique_countries_broadband['Rank Latency']

In [ ]:
%%time
## Transfer_post 7 ##
pd_unique_countries_broadband['Year'] = unique_countries_broadband['Year']

In [ ]:
%%time
## Transfer_post 7 ##
pd_unique_countries_broadband['Quarter'] = unique_countries_broadband['Quarter']

In [ ]:
pd_Mobile_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 8 ##
pd_Mobile_df['Name'] = Mobile_df['Name']

In [12]:
%%time
### cell 8 ###

unique_countries_mobile = Mobile_df.groupby('Name').count()
unique_countries_mobile.head()

CPU times: user 15.4 ms, sys: 20.8 ms, total: 36.3 ms
Wall time: 27.1 ms

,Number of Records,Devices,Tests,Avg. Avg U Kbps,Avg. Avg D Kbps,Avg Lat Ms,Avg. Pop2005,Rank Upload,Rank Download,Rank Latency,Year,Quarter
Name,,,,,,,,,,,,
Afghanistan,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000
Albania,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000
Algeria,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000
American Samoa,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000
Andorra,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000,22000

In [ ]:
pd_unique_countries_mobile = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 8 ##
pd_unique_countries_mobile['Number of Records'] = unique_countries_mobile['Number of Records']

In [ ]:
%%time
## Transfer_post 8 ##
pd_unique_countries_mobile['Devices'] = unique_countries_mobile['Devices']

In [ ]:
%%time
## Transfer_post 8 ##
pd_unique_countries_mobile['Tests'] = unique_countries_mobile['Tests']

In [ ]:
%%time
## Transfer_post 8 ##
pd_unique_countries_mobile['Avg. Avg U Kbps'] = unique_countries_mobile['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_post 8 ##
pd_unique_countries_mobile['Avg. Avg D Kbps'] = unique_countries_mobile['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_post 8 ##
pd_unique_countries_mobile['Avg Lat Ms'] = unique_countries_mobile['Avg Lat Ms']

In [ ]:
%%time
## Transfer_post 8 ##
pd_unique_countries_mobile['Avg. Pop2005'] = unique_countries_mobile['Avg. Pop2005']

In [ ]:
%%time
## Transfer_post 8 ##
pd_unique_countries_mobile['Rank Upload'] = unique_countries_mobile['Rank Upload']

In [ ]:
%%time
## Transfer_post 8 ##
pd_unique_countries_mobile['Rank Download'] = unique_countries_mobile['Rank Download']

In [ ]:
%%time
## Transfer_post 8 ##
pd_unique_countries_mobile['Rank Latency'] = unique_countries_mobile['Rank Latency']

In [ ]:
%%time
## Transfer_post 8 ##
pd_unique_countries_mobile['Year'] = unique_countries_mobile['Year']

In [ ]:
%%time
## Transfer_post 8 ##
pd_unique_countries_mobile['Quarter'] = unique_countries_mobile['Quarter']

## Insights

The following countries do have mobile speedtest data for all the years and quarters, thereby making less than 10 reports (one per quarter).

In [ ]:
pd_Mobile_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 9 ##
pd_Mobile_df['Name'] = Mobile_df['Name']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_Mobile_df['Number of Records'] = Mobile_df['Number of Records']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_Mobile_df['Devices'] = Mobile_df['Devices']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_Mobile_df['Tests'] = Mobile_df['Tests']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_Mobile_df['Avg. Avg U Kbps'] = Mobile_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_Mobile_df['Avg. Avg D Kbps'] = Mobile_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_Mobile_df['Avg Lat Ms'] = Mobile_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_Mobile_df['Avg. Pop2005'] = Mobile_df['Avg. Pop2005']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_Mobile_df['Rank Upload'] = Mobile_df['Rank Upload']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_Mobile_df['Rank Download'] = Mobile_df['Rank Download']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_Mobile_df['Rank Latency'] = Mobile_df['Rank Latency']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_Mobile_df['Year'] = Mobile_df['Year']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_Mobile_df['Quarter'] = Mobile_df['Quarter']

In [13]:
%%time
### cell 9 ###

# Check for missing values
Mobile_df.isna().any()

CPU times: user 29.7 ms, sys: 917 µs, total: 30.6 ms
Wall time: 32.1 ms

Name                 False
Number of Records    False
Devices              False
Tests                False
Avg. Avg U Kbps      False
Avg. Avg D Kbps      False
Avg Lat Ms           False
Avg. Pop2005         False
Rank Upload          False
Rank Download        False
Rank Latency         False
Year                 False
Quarter              False
dtype: bool

In [ ]:
pd_Broadband_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 10 ##
pd_Broadband_df['Name'] = Broadband_df['Name']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_Broadband_df['Number of Records'] = Broadband_df['Number of Records']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_Broadband_df['Devices'] = Broadband_df['Devices']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_Broadband_df['Tests'] = Broadband_df['Tests']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_Broadband_df['Avg. Avg U Kbps'] = Broadband_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_Broadband_df['Avg. Avg D Kbps'] = Broadband_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_Broadband_df['Avg Lat Ms'] = Broadband_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_Broadband_df['Avg. Pop2005'] = Broadband_df['Avg. Pop2005']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_Broadband_df['Rank Upload'] = Broadband_df['Rank Upload']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_Broadband_df['Rank Download'] = Broadband_df['Rank Download']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_Broadband_df['Rank Latency'] = Broadband_df['Rank Latency']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_Broadband_df['Year'] = Broadband_df['Year']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_Broadband_df['Quarter'] = Broadband_df['Quarter']

In [14]:
%%time
### cell 10 ###

Broadband_df.isna().any()

CPU times: user 18.5 ms, sys: 3.7 ms, total: 22.2 ms
Wall time: 18.3 ms

Name                 False
Number of Records    False
Devices              False
Tests                False
Avg. Avg U Kbps      False
Avg. Avg D Kbps      False
Avg Lat Ms           False
Avg. Pop2005         False
Rank Upload          False
Rank Download        False
Rank Latency         False
Year                 False
Quarter              False
dtype: bool

In [ ]:
pd_Mobile_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 11 ##
pd_Mobile_df['Name'] = Mobile_df['Name']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_Mobile_df['Number of Records'] = Mobile_df['Number of Records']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_Mobile_df['Devices'] = Mobile_df['Devices']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_Mobile_df['Tests'] = Mobile_df['Tests']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_Mobile_df['Avg. Avg U Kbps'] = Mobile_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_Mobile_df['Avg. Avg D Kbps'] = Mobile_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_Mobile_df['Avg Lat Ms'] = Mobile_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_Mobile_df['Avg. Pop2005'] = Mobile_df['Avg. Pop2005']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_Mobile_df['Rank Upload'] = Mobile_df['Rank Upload']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_Mobile_df['Rank Download'] = Mobile_df['Rank Download']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_Mobile_df['Rank Latency'] = Mobile_df['Rank Latency']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_Mobile_df['Year'] = Mobile_df['Year']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_Mobile_df['Quarter'] = Mobile_df['Quarter']

In [15]:
%%time
### cell 11 ###

Mobile_df.shape

CPU times: user 96 µs, sys: 19 µs, total: 115 µs
Wall time: 119 µs

(4974000, 13)

In [ ]:
pd_unique_countries_mobile = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 12 ##
pd_unique_countries_mobile['Year'] = unique_countries_mobile['Year']

In [16]:
%%time
### cell 12 ###

unique_countries_mobile[unique_countries_mobile.Year < 10]['Year']

CPU times: user 7.45 ms, sys: 684 µs, total: 8.13 ms
Wall time: 7.5 ms

Series([], Name: Year, dtype: int64)

In [ ]:
pd_unique_countries_broadband = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 13 ##
pd_unique_countries_broadband['Year'] = unique_countries_broadband['Year']

In [17]:
%%time
### cell 13 ###

unique_countries_broadband[unique_countries_broadband.Year < 10]['Year']

CPU times: user 2.9 ms, sys: 440 µs, total: 3.34 ms
Wall time: 2.67 ms

Series([], Name: Year, dtype: int64)

## Raw Download Speed Visualization

This visualization can be used to show change of values per country. The improvement values cannot be understood by laymen because an improvement of 50 Kbps **national average** (given) means differnt things to different countries based on economy, population, GDP, Infrastructure, etc.

In [ ]:
pd_Broadband_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 14 ##
pd_Broadband_df['Avg. Avg D Kbps'] = Broadband_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_pre 14 ##
pd_Broadband_df['Avg Lat Ms'] = Broadband_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_pre 14 ##
pd_Broadband_df['Avg. Avg U Kbps'] = Broadband_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_pre 14 ##
pd_Broadband_df['Name'] = Broadband_df['Name']

In [ ]:
pd_Mobile_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 14 ##
pd_Mobile_df['Avg. Avg D Kbps'] = Mobile_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_pre 14 ##
pd_Mobile_df['Avg Lat Ms'] = Mobile_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_pre 14 ##
pd_Mobile_df['Avg. Avg U Kbps'] = Mobile_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_pre 14 ##
pd_Mobile_df['Name'] = Mobile_df['Name']

In [18]:
%%time
### cell 14 ###

Mobile_Stats = Mobile_df.groupby('Name').agg(
    Change_Download=('Avg. Avg D Kbps', lambda x: list(x)[-1] - list(x)[0]),
    Change_Upload=('Avg. Avg U Kbps', lambda x: list(x)[-1] - list(x)[0]),
    Change_Latency=('Avg Lat Ms', lambda x: list(x)[-1] - list(x)[0])
)
Broadband_Stats = Broadband_df.groupby('Name').agg(
    Change_Download=('Avg. Avg D Kbps', lambda x: list(x)[-1] - list(x)[0]),
    Change_Upload=('Avg. Avg U Kbps', lambda x: list(x)[-1] - list(x)[0]),
    Change_Latency=('Avg Lat Ms', lambda x: list(x)[-1] - list(x)[0])
)
# fig = px.histogram(Mobile_Stats['Change_Download'],title='Frequency distribution of Mobile Speed change',
#                    labels={'count':'Frequency','value':'$\Delta Speed (Kpbs)$','variable':'property'},
#                    nbins=100)
# fig.show()

# fig = px.histogram(Broadband_Stats['Change_Download'],title='Frequency distribution of Broadband Speed change',
#                    labels={'count':'Frequency','value':'$\Delta Speed (Kpbs)$','variable':'property'},
#                    nbins=100)
# fig.show()
Total_Stats = pd.concat([Broadband_Stats['Change_Download'],Mobile_Stats['Change_Download']],axis=1)
Total_Stats.columns=['Mobile','Broadband']

# STEFANOS: Disable plotting
# fig = go.Figure(data=[go.Histogram(x=Broadband_Stats['Change_Download'],opacity=0.65,name='Broadband')])
# fig.add_trace(go.Histogram(x=Mobile_Stats['Change_Download'],opacity=0.65,name='Mobile'))
# fig.update_layout(barmode='overlay',
#                   title='Frequency Distribution of Speed change',
#                   xaxis_title="$\Delta\ Speed\ (Kbps)$", yaxis_title="Number of Countries",
#                   legend_title='Color')
# fig.show()

CPU times: user 4.85 s, sys: 859 ms, total: 5.71 s
Wall time: 5.7 s

In [ ]:
pd_Broadband_Stats = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 14 ##
pd_Broadband_Stats['Change_Download'] = Broadband_Stats['Change_Download']

In [ ]:
%%time
## Transfer_post 14 ##
pd_Broadband_Stats['Change_Upload'] = Broadband_Stats['Change_Upload']

In [ ]:
%%time
## Transfer_post 14 ##
pd_Broadband_Stats['Change_Latency'] = Broadband_Stats['Change_Latency']

In [ ]:
pd_Mobile_Stats = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 14 ##
pd_Mobile_Stats['Change_Download'] = Mobile_Stats['Change_Download']

In [ ]:
%%time
## Transfer_post 14 ##
pd_Mobile_Stats['Change_Upload'] = Mobile_Stats['Change_Upload']

In [ ]:
%%time
## Transfer_post 14 ##
pd_Mobile_Stats['Change_Latency'] = Mobile_Stats['Change_Latency']

It can see that most of the countries changed between -5000 Kbps to 5000 kbps. A common graph for all the countries is possible but makes it difficult to understand. Therefore it is better we split the countries into different visualizations, for seperate degrees of change

In [19]:
# STEFANOS: Disable plotting
# px.bar(Mobile_Stats,y='Change_Download',labels={'Name':'Country','Change_Download':'Observed Change'},title='Summary of all changes 2020 Q1 - 2022 Q2 ')

In [ ]:
pd_Broadband_Stats = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 15 ##
pd_Broadband_Stats['Change_Download'] = Broadband_Stats['Change_Download']

In [20]:
%%time
### cell 15 ###

#ImprovedCountries_M = Mobile_Stats[(Mobile_Stats['Change_Download'] < 3000) &
#                                (Mobile_Stats['Change_Download'] >0)]
#px.bar(ImprovedCountries_M,y='Change_Download',labels={'Name':'Country','Change_Download':'Improved Download Speed'},title='Countries that improved download speeds')

ImprovedCountries_B = Broadband_Stats[(Broadband_Stats['Change_Download'] < 3000) &
                                (Broadband_Stats['Change_Download'] > 0)]

# STEFANOS: Disable plotting
# fig = go.Figure()
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=ImprovedCountries_B['Change_Download'],opacity=0.6,name='Broadband'))
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=Mobile_Stats.query("index in @ImprovedCountries_B.index")['Change_Download'],opacity=0.6,name='Mobile'))
# fig.update_layout(barmode='group',
#                   title='Bar Chart of Speed change',
#                   xaxis_title="Country", yaxis_title="Improved Speed (Kbps)",
#                   legend_title='Color')
# fig.show()

CPU times: user 6.29 ms, sys: 3.64 ms, total: 9.93 ms
Wall time: 21 ms

In [ ]:
pd_Broadband_Stats = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 16 ##
pd_Broadband_Stats['Change_Download'] = Broadband_Stats['Change_Download']

In [ ]:
pd_ImprovedCountries_B = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 16 ##
pd_ImprovedCountries_B['Change_Upload'] = ImprovedCountries_B['Change_Upload']

In [ ]:
%%time
## Transfer_pre 16 ##
pd_ImprovedCountries_B['Change_Latency'] = ImprovedCountries_B['Change_Latency']

In [ ]:
%%time
## Transfer_pre 16 ##
pd_ImprovedCountries_B['Change_Download'] = ImprovedCountries_B['Change_Download']

In [21]:
%%time
### cell 16 ###

#ImprovedCountries2 = Mobile_Stats[(Mobile_Stats['Change_Download'] >= 10000)]
#px.bar(ImprovedCountries2,y='Change_Download',labels={'Name':'Country','Change_Download':'Improved Download Speed'},title='Countries that improved download speeds')
#ImprovedCountries_M = Mobile_Stats[(Mobile_Stats['Change_Download'] < 8000) &
#                                (Mobile_Stats['Change_Download'] >3000)]
#px.bar(ImprovedCountries_M,y='Change_Download',labels={'Name':'Country','Change_Download':'Improved Download Speed'},title='Countries that improved download speeds')

ImprovedCountries_B = Broadband_Stats[(Broadband_Stats['Change_Download'] < 8000) &
                                (Broadband_Stats['Change_Download'] > 3000)]
# STEFANOS: Disable plotting
# fig = go.Figure()
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=ImprovedCountries_B['Change_Download'],opacity=0.6,name='Broadband'))
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=Mobile_Stats.query("index in @ImprovedCountries_B.index")['Change_Download'],opacity=0.6,name='Mobile'))
# fig.update_layout(barmode='group',
#                   title='Bar Chart of Speed change',
#                   xaxis_title="Country", yaxis_title="Improved Speed (Kbps)",
#                   legend_title='Color')
# fig.show()

CPU times: user 5.38 ms, sys: 259 µs, total: 5.64 ms
Wall time: 4.57 ms

In [ ]:
pd_Broadband_Stats = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 17 ##
pd_Broadband_Stats['Change_Download'] = Broadband_Stats['Change_Download']

In [ ]:
pd_ImprovedCountries_B = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 17 ##
pd_ImprovedCountries_B['Change_Upload'] = ImprovedCountries_B['Change_Upload']

In [ ]:
%%time
## Transfer_pre 17 ##
pd_ImprovedCountries_B['Change_Latency'] = ImprovedCountries_B['Change_Latency']

In [ ]:
%%time
## Transfer_pre 17 ##
pd_ImprovedCountries_B['Change_Download'] = ImprovedCountries_B['Change_Download']

In [22]:
%%time
### cell 17 ###

ImprovedCountries_B = Broadband_Stats[(Broadband_Stats['Change_Download'] < 16000) &
                                (Broadband_Stats['Change_Download'] > 8000)]
# STEFANOS: Disable plotting
# fig = go.Figure()
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=ImprovedCountries_B['Change_Download'],opacity=0.6,name='Broadband'))
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=Mobile_Stats.query("index in @ImprovedCountries_B.index")['Change_Download'],opacity=0.6,name='Mobile'))
# fig.update_layout(barmode='group',
#                   title='Bar Chart of Speed change',
#                   xaxis_title="Country", yaxis_title="Improved Speed (Kbps)",
#                   legend_title='Color')
# fig.show()

CPU times: user 5.45 ms, sys: 0 ns, total: 5.45 ms
Wall time: 4.63 ms

In [ ]:
pd_Broadband_Stats = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 18 ##
pd_Broadband_Stats['Change_Download'] = Broadband_Stats['Change_Download']

In [ ]:
pd_ImprovedCountries_B = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 18 ##
pd_ImprovedCountries_B['Change_Upload'] = ImprovedCountries_B['Change_Upload']

In [ ]:
%%time
## Transfer_pre 18 ##
pd_ImprovedCountries_B['Change_Latency'] = ImprovedCountries_B['Change_Latency']

In [ ]:
%%time
## Transfer_pre 18 ##
pd_ImprovedCountries_B['Change_Download'] = ImprovedCountries_B['Change_Download']

In [23]:
%%time
### cell 18 ###

ImprovedCountries_B = Broadband_Stats[(Broadband_Stats['Change_Download'] < 60000) &
                                (Broadband_Stats['Change_Download'] > 16000)]
# STEFANOS: Disable plotting
# fig = go.Figure()
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=ImprovedCountries_B['Change_Download'],opacity=0.6,name='Broadband'))
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=Mobile_Stats.query("index in @ImprovedCountries_B.index")['Change_Download'],opacity=0.6,name='Mobile'))
# fig.update_layout(barmode='group',
#                   title='Bar Chart of Speed change',
#                   xaxis_title="Country", yaxis_title="Improved Speed (Kbps)",
#                   legend_title='Color')
# fig.show()

CPU times: user 4.48 ms, sys: 0 ns, total: 4.48 ms
Wall time: 3.53 ms

In [ ]:
pd_Broadband_Stats = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 19 ##
pd_Broadband_Stats['Change_Download'] = Broadband_Stats['Change_Download']

In [ ]:
pd_ImprovedCountries_B = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 19 ##
pd_ImprovedCountries_B['Change_Upload'] = ImprovedCountries_B['Change_Upload']

In [ ]:
%%time
## Transfer_pre 19 ##
pd_ImprovedCountries_B['Change_Latency'] = ImprovedCountries_B['Change_Latency']

In [ ]:
%%time
## Transfer_pre 19 ##
pd_ImprovedCountries_B['Change_Download'] = ImprovedCountries_B['Change_Download']

In [24]:
%%time
### cell 19 ###

ImprovedCountries_B = Broadband_Stats[(Broadband_Stats['Change_Download'] >= 60000)]
# STEFANOS: Disable plotting
# fig = go.Figure()
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=ImprovedCountries_B['Change_Download'],opacity=0.6,name='Broadband'))
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=Mobile_Stats.query("index in @ImprovedCountries_B.index")['Change_Download'],opacity=0.6,name='Mobile'))
# fig.update_layout(barmode='group',
#                   title='Bar Chart of Speed change',
#                   xaxis_title="Country", yaxis_title="Improved Speed (Kbps)",
#                   legend_title='Color')
# fig.show()

CPU times: user 5.94 ms, sys: 0 ns, total: 5.94 ms
Wall time: 11.3 ms

In [ ]:
pd_Broadband_Stats = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 20 ##
pd_Broadband_Stats['Change_Download'] = Broadband_Stats['Change_Download']

In [ ]:
pd_ImprovedCountries_B = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 20 ##
pd_ImprovedCountries_B['Change_Upload'] = ImprovedCountries_B['Change_Upload']

In [ ]:
%%time
## Transfer_pre 20 ##
pd_ImprovedCountries_B['Change_Latency'] = ImprovedCountries_B['Change_Latency']

In [ ]:
%%time
## Transfer_pre 20 ##
pd_ImprovedCountries_B['Change_Download'] = ImprovedCountries_B['Change_Download']

In [25]:
%%time
### cell 20 ###

#DeterioratedSpeeds = Mobile_Stats[(Mobile_Stats['Change_Download'] < 0 )]
#px.bar(DeterioratedSpeeds,y='Change_Download',labels={'Name':'Country','Change_Download':'Improved Download Speed'},title='Decreasing Countries\' download speeds')
ImprovedCountries_B = Broadband_Stats[(Broadband_Stats['Change_Download'] < 0)]
Countries = ImprovedCountries_B.index

# STEFANOS: Disable plotting
# fig = go.Figure()
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=ImprovedCountries_B['Change_Download'],opacity=0.6,name='Broadband'))
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=Mobile_Stats.query("index in @ImprovedCountries_B.index")['Change_Download'],opacity=0.6,name='Mobile'))
# fig.update_layout(barmode='group',
#                   title='Bar Chart of Speed change',
#                   xaxis_title="Country", yaxis_title="Improved Speed (Kbps)",
#                   legend_title='Color')
# fig.show()

CPU times: user 2.45 ms, sys: 402 µs, total: 2.85 ms
Wall time: 2.31 ms

In [ ]:
pd_Mobile_Stats = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 21 ##
pd_Mobile_Stats['Change_Download'] = Mobile_Stats['Change_Download']

In [26]:
%%time
### cell 21 ###

Mobile_Stats.sort_values(by=['Change_Download'])

CPU times: user 3.13 ms, sys: 597 µs, total: 3.73 ms
Wall time: 2.43 ms

                      Change_Download  Change_Upload  Change_Latency
Name
Svalbard                       -60722          -7622              26
Cook Islands                   -53299         -12437              96
Kiribati                       -16481          -6388             323
Cuba                           -13664          -3164              22
Lesotho                        -10968            149               2
...                               ...            ...             ...
Bahrain                        112317           7053               1
United Arab Emirates           113202           6452               3
Kuwait                         120812           9258              -2
Qatar                          121470           6862               7
Korea, Republic of             144033           7028              -7

[236 rows x 3 columns]

In [ ]:
pd_Broadband_Stats = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 22 ##
pd_Broadband_Stats['Change_Download'] = Broadband_Stats['Change_Download']

In [27]:
%%time
### cell 22 ###

Broadband_Stats.sort_values(by=['Change_Download'])

CPU times: user 4.72 ms, sys: 132 µs, total: 4.85 ms
Wall time: 3.35 ms

,Change_Download,Change_Upload,Change_Latency
Name,,,
Marshall Islands,-9495,-2082,-13
Comoros,-7547,-18156,38
United States Minor Outlying Islands,-7465,-18425,461
Guinea-Bissau,-5363,-2684,30
Cape Verde,-4525,-8908,-10
...,...,...,...
France,106223,82203,-10
Uruguay,109183,21217,-18
China,127467,23571,3
Chile,131498,111798,-12
"Korea, Democratic People's Republic of",185155,63642,-76

Different graphs are used to show different degrees of Average download speed change for each country. These are the capacities by which countries have changed. 

From the above graphs it can be seen that **China** has improved the most average (boardband) download speed and **Antarctica** has lost the most average download internet speed (broadband). Meanwhile **Korea** has the highest improvement in Mobile internet download speed, while **Cook Islands** has lost the most average mobile download speed

These metrics can be misleading as they show average speed change for the whole country. The infrastructure investment/deterioration of the country can only be known after the number is multiplied by population of the country.

## Percentage Download speed Visualization

In this view, we have normalized all improvements or depreciation to the original value, therefore large countries such as china which already have large infrastructure will be given less weightage and small countries that are developing would be given more preference. This view can be used everywhere as the values are normalized to percentages. Therefore larger internet speed nations will be given lower priority to the smaller speed nations. This is NOT a metric of a nation's total bandwidth as that will require denormalization with the nation's population. This metric can be used to compare the rate of national speed improvement between nations.

In [ ]:
pd_Broadband_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 23 ##
pd_Broadband_df['Avg. Avg D Kbps'] = Broadband_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_pre 23 ##
pd_Broadband_df['Avg Lat Ms'] = Broadband_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_pre 23 ##
pd_Broadband_df['Avg. Avg U Kbps'] = Broadband_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_pre 23 ##
pd_Broadband_df['Name'] = Broadband_df['Name']

In [ ]:
pd_Mobile_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 23 ##
pd_Mobile_df['Avg. Avg D Kbps'] = Mobile_df['Avg. Avg D Kbps']

In [ ]:
%%time
## Transfer_pre 23 ##
pd_Mobile_df['Avg Lat Ms'] = Mobile_df['Avg Lat Ms']

In [ ]:
%%time
## Transfer_pre 23 ##
pd_Mobile_df['Avg. Avg U Kbps'] = Mobile_df['Avg. Avg U Kbps']

In [ ]:
%%time
## Transfer_pre 23 ##
pd_Mobile_df['Name'] = Mobile_df['Name']

In [28]:
%%time
### cell 23 ###

Mobile_Stats_relative = Mobile_df.groupby('Name').agg(
    Change_Download=('Avg. Avg D Kbps', lambda x: (list(x)[-1] - list(x)[0])/list(x)[0]),
    Change_Upload=('Avg. Avg U Kbps', lambda x: (list(x)[-1] - list(x)[0])/list(x)[0]),
    Change_Latency=('Avg Lat Ms', lambda x: (list(x)[-1] - list(x)[0])/list(x)[0])
)
Broadband_Stats_relative = Broadband_df.groupby('Name').agg(
    Change_Download=('Avg. Avg D Kbps', lambda x: (list(x)[-1] - list(x)[0])/list(x)[0]),
    Change_Upload=('Avg. Avg U Kbps', lambda x: (list(x)[-1] - list(x)[0])/list(x)[0]),
    Change_Latency=('Avg Lat Ms', lambda x: (list(x)[-1] - list(x)[0])/list(x)[0])
)

CPU times: user 8.67 s, sys: 569 ms, total: 9.24 s
Wall time: 9.23 s

In [ ]:
pd_Broadband_Stats_relative = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 23 ##
pd_Broadband_Stats_relative['Change_Download'] = Broadband_Stats_relative['Change_Download']

In [ ]:
%%time
## Transfer_post 23 ##
pd_Broadband_Stats_relative['Change_Upload'] = Broadband_Stats_relative['Change_Upload']

In [ ]:
%%time
## Transfer_post 23 ##
pd_Broadband_Stats_relative['Change_Latency'] = Broadband_Stats_relative['Change_Latency']

In [ ]:
pd_Mobile_Stats_relative = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 23 ##
pd_Mobile_Stats_relative['Change_Download'] = Mobile_Stats_relative['Change_Download']

In [ ]:
%%time
## Transfer_post 23 ##
pd_Mobile_Stats_relative['Change_Upload'] = Mobile_Stats_relative['Change_Upload']

In [ ]:
%%time
## Transfer_post 23 ##
pd_Mobile_Stats_relative['Change_Latency'] = Mobile_Stats_relative['Change_Latency']

In [ ]:
pd_ImprovedCountries_B = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 24 ##
pd_ImprovedCountries_B['Change_Upload'] = ImprovedCountries_B['Change_Upload']

In [ ]:
%%time
## Transfer_pre 24 ##
pd_ImprovedCountries_B['Change_Latency'] = ImprovedCountries_B['Change_Latency']

In [ ]:
%%time
## Transfer_pre 24 ##
pd_ImprovedCountries_B['Change_Download'] = ImprovedCountries_B['Change_Download']

In [ ]:
pd_Broadband_Stats_relative = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 24 ##
pd_Broadband_Stats_relative['Change_Download'] = Broadband_Stats_relative['Change_Download']

In [29]:
%%time
### cell 24 ###

ImprovedCountries_B = Broadband_Stats_relative[(Broadband_Stats_relative['Change_Download'] >= 2)]
# STEFANOS: Disable plotting
# fig = go.Figure()
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=ImprovedCountries_B['Change_Download'],opacity=0.6,name='Broadband'))
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=Mobile_Stats_relative.query("index in @ImprovedCountries_B.index")['Change_Download'],opacity=0.6,name='Mobile'))
# fig.update_layout(barmode='group',
#                   title='Bar Chart of Relative Speed change',
#                   xaxis_title="Country", yaxis_title="Relative Improvement of Speed",
#                   legend_title='Color')
# fig.show()

CPU times: user 7.55 ms, sys: 353 µs, total: 7.9 ms
Wall time: 6.61 ms

In [ ]:
pd_ImprovedCountries_B = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 25 ##
pd_ImprovedCountries_B['Change_Upload'] = ImprovedCountries_B['Change_Upload']

In [ ]:
%%time
## Transfer_pre 25 ##
pd_ImprovedCountries_B['Change_Latency'] = ImprovedCountries_B['Change_Latency']

In [ ]:
%%time
## Transfer_pre 25 ##
pd_ImprovedCountries_B['Change_Download'] = ImprovedCountries_B['Change_Download']

In [ ]:
pd_Broadband_Stats_relative = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 25 ##
pd_Broadband_Stats_relative['Change_Download'] = Broadband_Stats_relative['Change_Download']

In [30]:
%%time
### cell 25 ###

ImprovedCountries_B = Broadband_Stats_relative[(Broadband_Stats_relative['Change_Download'] >= 1) & (Broadband_Stats_relative['Change_Download'] < 2)]
# STEFANOS: Disable plotting
# fig = go.Figure()
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=ImprovedCountries_B['Change_Download'],opacity=0.6,name='Broadband'))
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=Mobile_Stats_relative.query("index in @ImprovedCountries_B.index")['Change_Download'],opacity=0.6,name='Mobile'))
# fig.update_layout(barmode='group',
#                   title='Bar Chart of Relative Speed change',
#                   xaxis_title="Country", yaxis_title="Relative Improvement of Speed",
#                   legend_title='Color')
# fig.show()

CPU times: user 5.36 ms, sys: 189 µs, total: 5.55 ms
Wall time: 4.39 ms

In [ ]:
pd_ImprovedCountries_B = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 26 ##
pd_ImprovedCountries_B['Change_Upload'] = ImprovedCountries_B['Change_Upload']

In [ ]:
%%time
## Transfer_pre 26 ##
pd_ImprovedCountries_B['Change_Latency'] = ImprovedCountries_B['Change_Latency']

In [ ]:
%%time
## Transfer_pre 26 ##
pd_ImprovedCountries_B['Change_Download'] = ImprovedCountries_B['Change_Download']

In [ ]:
pd_Broadband_Stats_relative = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 26 ##
pd_Broadband_Stats_relative['Change_Download'] = Broadband_Stats_relative['Change_Download']

In [31]:
%%time
### cell 26 ###

ImprovedCountries_B = Broadband_Stats_relative[(Broadband_Stats_relative['Change_Download'] >= 0.5) & (Broadband_Stats_relative['Change_Download'] < 1)]
# STEFANOS: Disable plotting
# fig = go.Figure()
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=ImprovedCountries_B['Change_Download'],opacity=0.6,name='Broadband'))
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=Mobile_Stats_relative.query("index in @ImprovedCountries_B.index")['Change_Download'],opacity=0.6,name='Mobile'))
# fig.update_layout(barmode='group',
#                   title='Bar Chart of Relative Speed change',
#                   xaxis_title="Country", yaxis_title="Relative Improvement of Speed",
#                   legend_title='Color')
# fig.show()

CPU times: user 5.56 ms, sys: 0 ns, total: 5.56 ms
Wall time: 4.53 ms

In [ ]:
pd_ImprovedCountries_B = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 27 ##
pd_ImprovedCountries_B['Change_Upload'] = ImprovedCountries_B['Change_Upload']

In [ ]:
%%time
## Transfer_pre 27 ##
pd_ImprovedCountries_B['Change_Latency'] = ImprovedCountries_B['Change_Latency']

In [ ]:
%%time
## Transfer_pre 27 ##
pd_ImprovedCountries_B['Change_Download'] = ImprovedCountries_B['Change_Download']

In [ ]:
pd_Broadband_Stats_relative = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 27 ##
pd_Broadband_Stats_relative['Change_Download'] = Broadband_Stats_relative['Change_Download']

In [32]:
%%time
### cell 27 ###

ImprovedCountries_B = Broadband_Stats_relative[(Broadband_Stats_relative['Change_Download'] >= 0.2) & (Broadband_Stats_relative['Change_Download'] < 0.5)]
# STEFANOS: Disable plotting
# fig = go.Figure()
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=ImprovedCountries_B['Change_Download'],opacity=0.6,name='Broadband'))
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=Mobile_Stats_relative.query("index in @ImprovedCountries_B.index")['Change_Download'],opacity=0.6,name='Mobile'))
# fig.update_layout(barmode='group',
#                   title='Bar Chart of Relative Speed change',
#                   xaxis_title="Country", yaxis_title="Relative Improvement of Speed",
#                   legend_title='Color')
# fig.show()

CPU times: user 4.94 ms, sys: 129 µs, total: 5.07 ms
Wall time: 4.14 ms

In [ ]:
pd_ImprovedCountries_B = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 28 ##
pd_ImprovedCountries_B['Change_Upload'] = ImprovedCountries_B['Change_Upload']

In [ ]:
%%time
## Transfer_pre 28 ##
pd_ImprovedCountries_B['Change_Latency'] = ImprovedCountries_B['Change_Latency']

In [ ]:
%%time
## Transfer_pre 28 ##
pd_ImprovedCountries_B['Change_Download'] = ImprovedCountries_B['Change_Download']

In [ ]:
pd_Broadband_Stats_relative = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 28 ##
pd_Broadband_Stats_relative['Change_Download'] = Broadband_Stats_relative['Change_Download']

In [33]:
%%time
### cell 28 ###

ImprovedCountries_B = Broadband_Stats_relative[(Broadband_Stats_relative['Change_Download'] >= 0) & (Broadband_Stats_relative['Change_Download'] < 0.2)]
# STEFANOS: Disable plotting
# fig = go.Figure()
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=ImprovedCountries_B['Change_Download'],opacity=0.6,name='Broadband'))
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=Mobile_Stats_relative.query("index in @ImprovedCountries_B.index")['Change_Download'],opacity=0.6,name='Mobile'))
# fig.update_layout(barmode='group',
#                   title='Bar Chart of Relative Speed change',
#                   xaxis_title="Country", yaxis_title="Relative Improvement of Speed",
#                   legend_title='Color')
# fig.show()

CPU times: user 4.63 ms, sys: 85 µs, total: 4.72 ms
Wall time: 3.86 ms

In [ ]:
pd_ImprovedCountries_B = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 29 ##
pd_ImprovedCountries_B['Change_Upload'] = ImprovedCountries_B['Change_Upload']

In [ ]:
%%time
## Transfer_pre 29 ##
pd_ImprovedCountries_B['Change_Latency'] = ImprovedCountries_B['Change_Latency']

In [ ]:
%%time
## Transfer_pre 29 ##
pd_ImprovedCountries_B['Change_Download'] = ImprovedCountries_B['Change_Download']

In [ ]:
pd_Broadband_Stats_relative = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 29 ##
pd_Broadband_Stats_relative['Change_Download'] = Broadband_Stats_relative['Change_Download']

In [34]:
%%time
### cell 29 ###

ImprovedCountries_B = Broadband_Stats_relative[(Broadband_Stats_relative['Change_Download'] < 0)]
# STEFANOS: Disable plotting
# fig = go.Figure()
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=ImprovedCountries_B['Change_Download'],opacity=0.6,name='Broadband'))
# fig.add_trace(go.Bar(x=ImprovedCountries_B.index,y=Mobile_Stats_relative.query("index in @ImprovedCountries_B.index")['Change_Download'],opacity=0.6,name='Mobile'))
# fig.update_layout(barmode='group',
#                   title='Bar Chart of Relative Speed change',
#                   xaxis_title="Country", yaxis_title="Relative Improvement of Speed",
#                   legend_title='Color')
# fig.show()

CPU times: user 2.89 ms, sys: 0 ns, total: 2.89 ms
Wall time: 2.24 ms

In [ ]:
pd_Broadband_Stats_relative = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 30 ##
pd_Broadband_Stats_relative['Change_Download'] = Broadband_Stats_relative['Change_Download']

In [35]:
%%time
### cell 30 ###

Broadband_Stats_relative.sort_values(by=['Change_Download'])

CPU times: user 4.36 ms, sys: 48 µs, total: 4.41 ms
Wall time: 3.81 ms

,Change_Download,Change_Upload,Change_Latency
Name,,,
Marshall Islands,-0.838855,-0.435747,-0.141304
Comoros,-0.726721,-0.973147,0.236025
Guinea-Bissau,-0.492244,-0.403185,0.405405
United States Minor Outlying Islands,-0.406104,-0.920698,1.945148
Saint Helena,-0.399552,-0.162749,-0.015524
...,...,...,...
Nauru,6.308000,23.425648,-0.641304
Tonga,6.369925,5.602930,-0.219388
Wallis and Futuna Islands,7.068718,8.957143,-0.109718
Kiribati,11.596980,54.074689,-0.685371
British Indian Ocean Territory,19.223150,3.389358,-0.433834

In [ ]:
pd_Mobile_Stats_relative = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 31 ##
pd_Mobile_Stats_relative['Change_Download'] = Mobile_Stats_relative['Change_Download']

In [36]:
%%time
### cell 31 ###

Mobile_Stats_relative.sort_values(by=['Change_Download'])

CPU times: user 7.27 ms, sys: 455 µs, total: 7.73 ms
Wall time: 6.71 ms

                           Change_Download  Change_Upload  Change_Latency
Name
Wallis and Futuna Islands        -0.991780      -0.973705        0.237410
Cook Islands                     -0.821603      -0.653204        3.692308
Kiribati                         -0.801917      -0.697532        1.362869
Cuba                             -0.567984      -0.303181        0.176000
Timor-Leste                      -0.543723      -0.483994       -0.027027
...                                    ...            ...             ...
Cayman Islands                    3.223961       1.128062       -0.026316
Mauritania                        3.328165       4.981119        0.153846
Guinea-Bissau                     3.554574       1.512042       -0.583333
Iraq                              3.821616       3.225883       -0.500000
Saint Pierre and Miquelon        14.014474       4.000000       -0.424242

[236 rows x 3 columns]

In this view we have **Saint Pierre and Miquelon** improving the most relative to its baseline speed and **Wallis and Futuna Islands** losing almost all of its original national average download speed for mobile devices. On the other hand, we have **Antarctica** losing 0.82x its original average speed while Tongo improve its speed by 5x for broadband downloads. Either ends of this view of data would be filled with countries that have low download speeds to begin with, as in that case a minute improvement would also be amplified due to its relative nature.