In [1]:
%load_ext cudf.pandas

In [2]:
import sys, os
sys.path.insert(0, os.path.abspath('/home/ElasticNotebook'))
%load_ext ElasticNotebook
from elastic.core.common.pandas import compare_df
import pickle
import cudf

Enabled rmm statistics

# Exploratory Data Analysis


Exploratory Data Analysis on dataset 'SampleSuperstore' to find out the patterns in data and to analyse the business trends in order to determine the weak areas that needs to be worked on in order to make more profit

# Importing Libraries

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns
import os
# STEFANOS: Conditionally import Modin Pandas
if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    # STEFANOS: Import Modin Pandas
    import os
    os.environ["MODIN_ENGINE"] = "ray"
    import ray
    ray.init(num_cpus=int(os.environ['MODIN_CPUS']), runtime_env={'env_vars': {'__MODIN_AUTOIMPORT_PANDAS__': '1'}})
    import modin.pandas as pd
else:
    # STEFANOS: Import regular Pandas
    import pandas as pd

# Reading the data

In [4]:
%%time
### cell 0 ###

data=pd.read_csv("/home/dias-benchmarks/notebooks/roopacalistus/retail-supermarket-store-analysis/input/superstore/SampleSuperstore.csv")

CPU times: user 30.8 ms, sys: 68.5 ms, total: 99.3 ms
Wall time: 95 ms

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Ship Mode'] = data['Ship Mode']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Segment'] = data['Segment']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Country'] = data['Country']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['City'] = data['City']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['State'] = data['State']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Postal Code'] = data['Postal Code']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Region'] = data['Region']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Category'] = data['Category']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Sub-Category'] = data['Sub-Category']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Sales'] = data['Sales']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Quantity'] = data['Quantity']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Discount'] = data['Discount']

In [ ]:
%%time
## Transfer_post 0 ##
pd_data['Profit'] = data['Profit']

# -- STEFANOS -- Replicate Data

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Ship Mode'] = data['Ship Mode']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Segment'] = data['Segment']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Country'] = data['Country']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['City'] = data['City']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['State'] = data['State']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Postal Code'] = data['Postal Code']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Region'] = data['Region']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Category'] = data['Category']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Sub-Category'] = data['Sub-Category']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Sales'] = data['Sales']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Quantity'] = data['Quantity']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Discount'] = data['Discount']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_data['Profit'] = data['Profit']

In [5]:
%%time
### cell 1 ###

# factor = 800
factor = 800
data = pd.concat([data]*factor)
data.info()

<class 'cudf.core.dataframe.DataFrame'>
Index: 7995200 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Dtype
---  ------        -----
 0   Ship Mode     object
 1   Segment       object
 2   Country       object
 3   City          object
 4   State         object
 5   Postal Code   int64
 6   Region        object
 7   Category      object
 8   Sub-Category  object
 9   Sales         float64
 10  Quantity      int64
 11  Discount      float64
 12  Profit        float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1.2+ GB
CPU times: user 868 ms, sys: 224 ms, total: 1.09 s
Wall time: 1.03 s

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 1 ##
pd_data['Ship Mode'] = data['Ship Mode']

In [ ]:
%%time
## Transfer_post 1 ##
pd_data['Segment'] = data['Segment']

In [ ]:
%%time
## Transfer_post 1 ##
pd_data['Country'] = data['Country']

In [ ]:
%%time
## Transfer_post 1 ##
pd_data['City'] = data['City']

In [ ]:
%%time
## Transfer_post 1 ##
pd_data['State'] = data['State']

In [ ]:
%%time
## Transfer_post 1 ##
pd_data['Postal Code'] = data['Postal Code']

In [ ]:
%%time
## Transfer_post 1 ##
pd_data['Region'] = data['Region']

In [ ]:
%%time
## Transfer_post 1 ##
pd_data['Category'] = data['Category']

In [ ]:
%%time
## Transfer_post 1 ##
pd_data['Sub-Category'] = data['Sub-Category']

In [ ]:
%%time
## Transfer_post 1 ##
pd_data['Sales'] = data['Sales']

In [ ]:
%%time
## Transfer_post 1 ##
pd_data['Quantity'] = data['Quantity']

In [ ]:
%%time
## Transfer_post 1 ##
pd_data['Discount'] = data['Discount']

In [ ]:
%%time
## Transfer_post 1 ##
pd_data['Profit'] = data['Profit']

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Ship Mode'] = data['Ship Mode']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Segment'] = data['Segment']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Country'] = data['Country']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['City'] = data['City']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['State'] = data['State']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Postal Code'] = data['Postal Code']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Region'] = data['Region']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Category'] = data['Category']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Sub-Category'] = data['Sub-Category']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Sales'] = data['Sales']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Quantity'] = data['Quantity']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Discount'] = data['Discount']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_data['Profit'] = data['Profit']

In [6]:
%%time
### cell 2 ###

data.head()

CPU times: user 4.29 ms, sys: 0 ns, total: 4.29 ms
Wall time: 3.26 ms

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 3 ##
pd_data['Ship Mode'] = data['Ship Mode']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_data['Segment'] = data['Segment']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_data['Country'] = data['Country']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_data['City'] = data['City']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_data['State'] = data['State']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_data['Postal Code'] = data['Postal Code']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_data['Region'] = data['Region']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_data['Category'] = data['Category']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_data['Sub-Category'] = data['Sub-Category']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_data['Sales'] = data['Sales']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_data['Quantity'] = data['Quantity']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_data['Discount'] = data['Discount']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_data['Profit'] = data['Profit']

In [7]:
%%time
### cell 3 ###

data.info()

<class 'cudf.core.dataframe.DataFrame'>
Index: 7995200 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Dtype
---  ------        -----
 0   Ship Mode     object
 1   Segment       object
 2   Country       object
 3   City          object
 4   State         object
 5   Postal Code   int64
 6   Region        object
 7   Category      object
 8   Sub-Category  object
 9   Sales         float64
 10  Quantity      int64
 11  Discount      float64
 12  Profit        float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1.2+ GB
CPU times: user 11 ms, sys: 719 µs, total: 11.7 ms
Wall time: 9.75 ms

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 4 ##
pd_data['Ship Mode'] = data['Ship Mode']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_data['Segment'] = data['Segment']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_data['Country'] = data['Country']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_data['City'] = data['City']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_data['State'] = data['State']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_data['Postal Code'] = data['Postal Code']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_data['Region'] = data['Region']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_data['Category'] = data['Category']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_data['Sub-Category'] = data['Sub-Category']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_data['Sales'] = data['Sales']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_data['Quantity'] = data['Quantity']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_data['Discount'] = data['Discount']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_data['Profit'] = data['Profit']

In [8]:
%%time
### cell 4 ###

data.duplicated().sum()

CPU times: user 22 ms, sys: 7.78 ms, total: 29.8 ms
Wall time: 27.7 ms

7985223

#### So, there are 17 duplicate entries and let us drop them.

In [9]:
# STEFANOS: Disable this. It undos the data replication.
# data.drop_duplicates(inplace= True)

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 5 ##
pd_data['Ship Mode'] = data['Ship Mode']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_data['Segment'] = data['Segment']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_data['Country'] = data['Country']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_data['City'] = data['City']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_data['State'] = data['State']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_data['Postal Code'] = data['Postal Code']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_data['Region'] = data['Region']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_data['Category'] = data['Category']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_data['Sub-Category'] = data['Sub-Category']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_data['Sales'] = data['Sales']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_data['Quantity'] = data['Quantity']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_data['Discount'] = data['Discount']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_data['Profit'] = data['Profit']

In [10]:
%%time
### cell 5 ###

data.info()

<class 'cudf.core.dataframe.DataFrame'>
Index: 7995200 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Dtype
---  ------        -----
 0   Ship Mode     object
 1   Segment       object
 2   Country       object
 3   City          object
 4   State         object
 5   Postal Code   int64
 6   Region        object
 7   Category      object
 8   Sub-Category  object
 9   Sales         float64
 10  Quantity      int64
 11  Discount      float64
 12  Profit        float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1.2+ GB
CPU times: user 11.5 ms, sys: 0 ns, total: 11.5 ms
Wall time: 9.11 ms

# Dropping unwanted columns

In [11]:
%%time
### cell 6 ###

data.drop(["Postal Code"], axis=1,inplace= True)

CPU times: user 175 µs, sys: 43 µs, total: 218 µs
Wall time: 223 µs

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 7 ##
pd_data['Ship Mode'] = data['Ship Mode']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_data['Segment'] = data['Segment']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_data['Country'] = data['Country']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_data['City'] = data['City']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_data['State'] = data['State']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_data['Region'] = data['Region']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_data['Category'] = data['Category']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_data['Sub-Category'] = data['Sub-Category']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_data['Sales'] = data['Sales']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_data['Quantity'] = data['Quantity']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_data['Discount'] = data['Discount']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_data['Profit'] = data['Profit']

In [12]:
%%time
### cell 7 ###

data.info()

<class 'cudf.core.dataframe.DataFrame'>
Index: 7995200 entries, 0 to 9993
Data columns (total 12 columns):
 #   Column        Dtype
---  ------        -----
 0   Ship Mode     object
 1   Segment       object
 2   Country       object
 3   City          object
 4   State         object
 5   Region        object
 6   Category      object
 7   Sub-Category  object
 8   Sales         float64
 9   Quantity      int64
 10  Discount      float64
 11  Profit        float64
dtypes: float64(3), int64(1), object(8)
memory usage: 1.1+ GB
CPU times: user 9.21 ms, sys: 0 ns, total: 9.21 ms
Wall time: 7.54 ms

# Correlation between the data

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 8 ##
pd_data['Ship Mode'] = data['Ship Mode']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_data['Segment'] = data['Segment']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_data['Country'] = data['Country']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_data['City'] = data['City']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_data['State'] = data['State']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_data['Region'] = data['Region']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_data['Category'] = data['Category']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_data['Sub-Category'] = data['Sub-Category']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_data['Sales'] = data['Sales']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_data['Quantity'] = data['Quantity']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_data['Discount'] = data['Discount']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_data['Profit'] = data['Profit']

In [13]:
%%time
### cell 8 ###

data.corr(numeric_only=True)

CPU times: user 2.36 s, sys: 1.01 s, total: 3.38 s
Wall time: 3.37 s

             Sales  Quantity  Discount    Profit
Sales     1.000000  0.200795 -0.028190  0.479064
Quantity  0.200795  1.000000  0.008623  0.066253
Discount -0.028190  0.008623  1.000000 -0.219487
Profit    0.479064  0.066253 -0.219487  1.000000

In [14]:
# STEFANOS: Disable plotting
# sns.heatmap(data.corr(), annot=True)

# EDA

### Analysing the different kinds of Shipping Modes, Segments and categories mentioned in the data

## Shipping Mode

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 9 ##
pd_data['Ship Mode'] = data['Ship Mode']

In [15]:
%%time
### cell 9 ###

data["Ship Mode"].value_counts()

CPU times: user 18 s, sys: 666 ms, total: 18.6 s
Wall time: 18.6 s

Ship Mode
Standard Class    4774400
Second Class      1556000
First Class       1230400
Same Day           434400
Name: count, dtype: int64

In [16]:
# STEFANOS: Disable plotting
# sns.countplot(x= data['Ship Mode'])

## Different Segments

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 10 ##
pd_data['Segment'] = data['Segment']

In [17]:
%%time
### cell 10 ###

data["Segment"].value_counts()

CPU times: user 8.26 ms, sys: 8.05 ms, total: 16.3 ms
Wall time: 14.6 ms

Segment
Consumer       4152800
Corporate      2416000
Home Office    1426400
Name: count, dtype: int64

In [18]:
# STEFANOS: Disable plotting
# sns.countplot(x= data['Segment'])

## Categories of the items

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 11 ##
pd_data['Category'] = data['Category']

In [19]:
%%time
### cell 11 ###

data["Category"].value_counts()

CPU times: user 12.3 ms, sys: 4.04 ms, total: 16.3 ms
Wall time: 14.7 ms

Category
Office Supplies    4820800
Furniture          1696800
Technology         1477600
Name: count, dtype: int64

In [20]:
# STEFANOS: Disable plotting
# sns.countplot(x= data['Category'])

#### From the above plot we can conclude that Office Supplies Category has highest number of sales. Now let us see the sub-categories as well.

## Sub-categories of items

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 12 ##
pd_data['Sub-Category'] = data['Sub-Category']

In [21]:
%%time
### cell 12 ###

data["Sub-Category"].value_counts()

CPU times: user 15.2 ms, sys: 0 ns, total: 15.2 ms
Wall time: 13.9 ms

Sub-Category
Binders        1218400
Paper          1096000
Furnishings     765600
Phones          711200
Storage         676800
Art             636800
Accessories     620000
Chairs          493600
Appliances      372800
Labels          291200
Tables          255200
Envelopes       203200
Bookcases       182400
Fasteners       173600
Supplies        152000
Machines         92000
Copiers          54400
Name: count, dtype: int64

In [22]:
# STEFANOS: Disable plotting
# plt.figure(figsize=(15,15))
# plt.pie(data["Sub-Category"].value_counts(), labels= data["Sub-Category"].value_counts().index, autopct ="%2f")
# plt.show()

#### Here, Sub-Category with highest sale is Binder, follwed by Paper and Furnishings as second and third respectively.

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 13 ##
pd_data['State'] = data['State']

In [ ]:
%%time
## Transfer_pre 13 ##
pd_data['Profit'] = data['Profit']

In [23]:
%%time
### cell 13 ###

st_profit=data.groupby(["State"])["Profit"].sum().nlargest(20)

CPU times: user 11.8 ms, sys: 3.98 ms, total: 15.7 ms
Wall time: 13.9 ms

In [ ]:
%%time
## Transfer_post 13 ##
pd_st_profit = st_profit

In [ ]:
%%time
## Transfer_pre 14 ##
pd_st_profit = st_profit

In [24]:
%%time
### cell 14 ###

st_profit

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.48 µs

State
California       61105109.68
New York         59230838.88
Washington       26722121.36
Michigan         19570550.08
Virginia         14878360.32
Indiana          14706349.04
Georgia          13000034.64
Kentucky          8959757.28
Minnesota         8658549.92
Delaware          7981899.84
New Jersey        7818331.04
Wisconsin         6721440.32
Rhode Island      5828503.44
Maryland          5624943.04
Massachusetts     5428401.28
Missouri          5148968.40
Alabama           4629460.24
Oklahoma          3883164.80
Arkansas          3206949.68
Connecticut       2809193.44
Name: Profit, dtype: float64

In [25]:
# STEFANOS: Disable plotting
# plt.figure(figsize=(15,8))
# st_profit.plot.bar()

In [26]:
# STEFANOS: Disable plotting
# sns.lineplot(data=data, x="Discount", y= "Profit")

#### So we can see that when discount increases profit decreases

In [27]:
# STEFANOS: Disable plotting
# data.plot(kind="scatter",x="Sales",y="Profit", c="Discount", colormap="Set1",figsize=(10,10))

In this scatter plot we can clearly see that more sales does not mean more profit. It depends on discount as well. 
When Sales is high and there is low discount, the profit margin is higher.

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 15 ##
pd_data['State'] = data['State']

In [28]:
%%time
### cell 15 ###

data1= data.groupby("State")[["Sales","Profit"]].sum().sort_values(by="Sales", ascending=False)
# STEFANOS: Disable plotting
# data1[:].plot.bar(color = ["Green","Red"], figsize=(20,12))
# plt.title("Profit-Loss and Sales across States")
# plt.show()

CPU times: user 8.05 ms, sys: 12.5 ms, total: 20.6 ms
Wall time: 17.5 ms

California and New York generate more profit compared to the other states.

# Profit-Loss and Sales across Region

In [ ]:
pd_data = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 16 ##
pd_data['Region'] = data['Region']

In [ ]:
pd_data1 = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 16 ##
pd_data1['Sales'] = data1['Sales']

In [ ]:
%%time
## Transfer_pre 16 ##
pd_data1['Profit'] = data1['Profit']

In [29]:
%%time
### cell 16 ###

data1= data.groupby("Region")[["Sales","Profit"]].sum().sort_values(by="Sales", ascending=False)
# STEFANOS: Disable plotting
# data1[:].plot.bar(color = ["Blue","Red"], figsize=(10,7))
# plt.title("Profit-Loss and Sales across Region")
# plt.show()

CPU times: user 11.1 ms, sys: 7.68 ms, total: 18.8 ms
Wall time: 15.7 ms




# Conclusion:


1. The western region generates highest profit.
2. California, NewYork and Washington generates the most sales compared to the other places. 
3. The central region generates lowest profit. 
4. Texas, Pennsylvenia, Florida, Illinois, Ohio and some other states are generating loss with high sale. So we need to give some attention towards them.

Therefore, we have to work more on California and New York. Increase the sales in these states by reducing sales in states like Texas, Florida, Ohio. By decreasing the discount rates in Central region we can increase the profit. Finally we should increase the sale of Office Supplies category as they contribute more.