In [10]:
import pandas as pd
# csv_path = "./notebooks/lextoumbourou/feedback3-eda-hf-custom-trainer-sift/src/transfer_costs.csv"
# csv_path = "/home/dias-benchmarks/notebooks/aieducation/what-course-are-you-going-to-take/src/transfer_costs.csv"
# csv_path = "./notebooks/nickwan/creating-player-stats-using-tracking-data/src/transfer_costs.csv"
# csv_path = "/home/dias-benchmarks/new_notebooks/imdb/transfer_costs.csv"
# csv_path = "./notebooks/sanket7994/imdb-dataset-eda-project/src/transfer_costs.csv"
# csv_path = "./notebooks/joshuaswords/netflix-data-visualization/src/transfer_costs.csv"
# csv_path = "/home/dias-benchmarks/notebooks/aieducation/what-course-are-you-going-to-take/src/transfer_costs.csv"
# csv_path = "/home/dias-benchmarks/notebooks/saisandeepjallepalli/adidas-retail-eda-data-visualization/src/new_transfer_costs.csv"
# csv_path = "./notebooks/ampiiere/animal-crossing-villager-popularity-analysis/src/transfer_costs.csv"
# csv_path = "/home/dias-benchmarks/new_notebooks/imdb/transfer_costs.csv"
# csv_path = "./notebooks/aieducation/what-course-are-you-going-to-take/src/transfer_costs.csv"
csv_path = "./notebooks/dataranch/supermarket-sales-prediction-xgboost-fastai/src/transfer_costs.csv"
df = pd.read_csv(csv_path)

In [11]:
cpu_to_gpu_error_percentages = abs(df['cpu->gpu'] - df['cost-cpu->gpu']) / df['cpu->gpu']
gpu_to_cpu_error_percentages =  abs(df['gpu->cpu'] - df['cost-gpu->cpu']) / df['gpu->cpu']
cpu_mean = cpu_to_gpu_error_percentages.mean()
gpu_mean = gpu_to_cpu_error_percentages.mean()
# df['abs_cpu_error'] = abs(df['cpu->gpu'] - df['cost-cpu->gpu']) / df['cpu->gpu']
df['abs_gpu_error'] = abs(df['gpu->cpu'] - df['cost-gpu->cpu'])
df['gpu_to_cpu_error_percentages']=gpu_to_cpu_error_percentages
df = df.drop(columns=["cpu->gpu", "cost-cpu->gpu"])

In [16]:
gpu_mean

0.3469381299899846

In [3]:
# ['popul_df', 'vlgr_df']
mask = (
    (df['df_name'] == 'vlgr_df')
    & (df['cell_idx'] > 11)
    & df['df_col'].notna()
    # & (df['df_col'] == "num_ratings")
)# Apply the mask, sort by "abs_gpu_error" first, then by "cell_idx"
df[mask].sort_values(by=["gpu_to_cpu_error_percentages"], ascending=False).gpu_to_cpu_error_percentages.mean()
df[mask].sort_values(by=["cell_idx"]).head(50)

Empty DataFrame
Columns: [cell_idx, df_name, df_col, gpu->cpu, cost-gpu->cpu, abs_gpu_error, gpu_to_cpu_error_percentages]
Index: []

In [4]:
# Apply the mask, sort by "abs_gpu_error" first, then by "cell_idx"
df.sort_values(by=["gpu_to_cpu_error_percentages"], ascending=False).head(40)

,cell_idx,df_name,df_col,gpu->cpu,cost-gpu->cpu,abs_gpu_error,gpu_to_cpu_error_percentages
0,0,popul_df,tier,134.00,1.145096,132.854904,0.991455
217,25,style_ranking1,overall_ranking,3.53,0.056630,3.473370,0.983957
214,24,style_ranking1,overall_ranking,3.36,0.056630,3.303370,0.983146
216,24,style_ranking2,overall_ranking,3.05,0.056630,2.993370,0.981433
218,25,style_ranking2,overall_ranking,3.04,0.056630,2.983370,0.981372
220,25,style_ranking,overall_ranking,3.03,0.056630,2.973370,0.981310
222,26,style_ranking,overall_ranking,2.73,0.056630,2.673370,0.979256
1,0,popul_df,rank,3.51,1.145096,2.364904,0.673762
158,13,combined_df,Style 2,27.50,45.749887,18.249887,0.663632
156,13,combined_df,Hobby,27.90,46.056699,18.156699,0.650778
77,5,popul_df,tier,4.05,1.473202,2.576798,0.636246
207,23,combined_df,Catchphrase,28.30,46.300084,18.000084,0.636045
155,13,combined_df,Catchphrase,28.30,46.300084,18.000084,0.636045
224,27,combined_df,tier,10.40,16.986773,6.586773,0.633344
181,16,combined_df,Species,27.80,45.345720,17.545720,0.631141
167,14,combined_df,Style 1,28.00,45.670233,17.670233,0.631080
190,17,combined_df,Gender,27.80,45.263116,17.463116,0.628170
187,16,combined_df,Style 2,28.10,45.749887,17.649887,0.628110
185,16,combined_df,Catchphrase,28.60,46.300084,17.700084,0.618884
169,14,combined_df,Style 2,28.30,45.749887,17.449887,0.616604
191,18,combined_df,Gender,28.00,45.263116,17.263116,0.616540
193,19,combined_df,Gender,28.00,45.263116,17.263116,0.616540
137,12,combined_df,Favorite Song,30.10,48.593804,18.493804,0.614412
160,13,combined_df,Species,28.10,45.345720,17.245720,0.613727
173,14,combined_df,Catchphrase,28.70,46.300084,17.600084,0.613243
228,28,combined_df,Catchphrase,28.80,46.300084,17.500084,0.607642
157,13,combined_df,Favorite Song,30.30,48.593804,18.293804,0.603756
180,16,combined_df,overall_ranking,10.60,16.986773,6.386773,0.602526
161,13,combined_df,Personality,28.50,45.494701,16.994701,0.596305
183,16,combined_df,Personality,28.50,45.494701,16.994701,0.596305
174,14,combined_df,Color 2,28.50,45.347195,16.847195,0.591130
225,27,combined_df,Catchphrase,29.10,46.300084,17.200084,0.591068
205,23,combined_df,Personality,28.60,45.494701,16.894701,0.590724
184,16,combined_df,Hobby,29.00,46.056699,17.056699,0.588162
186,16,combined_df,Style 1,28.90,45.670233,16.770233,0.580285
145,12,combined_df,Filename,28.70,45.288193,16.588193,0.577986
166,14,combined_df,Gender,28.70,45.263116,16.563116,0.577112
209,24,combined_df,Style 2,29.10,45.749887,16.649887,0.572161
165,14,combined_df,Color 1,28.90,45.376696,16.476696,0.570128
208,24,combined_df,Style 1,29.10,45.670233,16.570233,0.569424

In [11]:
df[df.df_col == "tier"]

,cell_idx,df_name,df_col,gpu->cpu,cost-gpu->cpu,abs_gpu_error,gpu_to_cpu_error_percentages
0,0,popul_df,tier,133.00,2.011604,130.988396,0.984875
20,1,popul_df,tier,4.41,2.648802,1.761198,0.399365
57,3,popul_df,tier,3.18,2.648802,0.531198,0.167043
77,5,popul_df,tier,3.16,2.648802,0.511198,0.161771
87,10,popul_df,tier,2.87,2.648802,0.221198,0.077072
91,11,popul_df,tier,2.71,2.614167,0.095833,0.035363
111,12,popul_df,tier,3.10,2.614167,0.485833,0.156720
129,12,combined_df,tier,22.80,32.776941,9.976941,0.437585
147,13,combined_df,tier,12.00,32.776941,20.776941,1.731412
165,14,combined_df,tier,12.20,32.776941,20.576941,1.686634
178,16,combined_df,tier,19.30,32.776941,13.476941,0.698287
191,18,combined_df,tier,12.00,32.776941,20.776941,1.731412
193,19,combined_df,tier,11.60,32.776941,21.176941,1.825598
196,20,combined_df,tier,11.70,32.776941,21.076941,1.801448
201,22,combined_df,tier,11.80,32.776941,20.976941,1.777707
205,23,combined_df,tier,11.70,32.776941,21.076941,1.801448
208,24,combined_df,tier,11.40,32.776941,21.376941,1.875170
223,27,combined_df,tier,13.00,32.776941,19.776941,1.521303
226,28,combined_df,tier,39.10,32.776941,6.323059,0.161715

df[df.df_col == "num_critic_for_reviews"].sort_values(by="cell_idx")

In [22]:
df = df.sort_values(by="gpu_diff", ascending=False)

In [23]:
df_new = df[["df_name", "df_col", "gpu->cpu", "cost-gpu->cpu", "gpu_diff"]]

In [24]:
df_new[df_new["df_col"] == "cohesion"]

Empty DataFrame
Columns: [df_name, df_col, gpu->cpu, cost-gpu->cpu, gpu_diff]
Index: []