In [1]:
import sys, os

sys.path.insert(0, os.path.abspath("/home/ElasticNotebook"))
%load_ext ElasticNotebook
from elastic.core.common.pandas import compare_df
import pickle
import cudf

Enabled rmm statistics

# Imports

In [2]:
import numpy as np
import os

if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    # STEFANOS: Import Modin Pandas
    import os

    os.environ["MODIN_ENGINE"] = "ray"
    import ray

    ray.init(
        num_cpus=int(os.environ["MODIN_CPUS"]),
        runtime_env={"env_vars": {"__MODIN_AUTOIMPORT_PANDAS__": "1"}},
    )
    import modin.pandas as pd
else:
    # STEFANOS: Import regular Pandas
    import pandas as pd
import time

# Load Data

In [3]:
%%time
### cell 0 ###

train_df = pd.read_csv(
    "/home/dias-benchmarks/notebooks/lextoumbourou/feedback3-eda-hf-custom-trainer-sift/input/feedback-prize-english-language-learning/train.csv"
)
test_df = pd.read_csv(
    "/home/dias-benchmarks/notebooks/lextoumbourou/feedback3-eda-hf-custom-trainer-sift/input/feedback-prize-english-language-learning/test.csv"
)

CPU times: user 85 ms, sys: 16.1 ms, total: 101 ms
Wall time: 100 ms

In [ ]:
cudf_test_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_post 0 ##
cudf_test_df["text_id"] = test_df["text_id"]

In [ ]:
%%time
## Transfer_post 0 ##
cudf_test_df["full_text"] = test_df["full_text"]

In [ ]:
cudf_train_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train_df["text_id"] = train_df["text_id"]

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train_df["full_text"] = train_df["full_text"]

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train_df["grammar"] = train_df["grammar"]

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train_df["conventions"] = train_df["conventions"]

# -- STEFANOS -- Replicate Data

In [ ]:
cudf_test_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_test_df["text_id"] = test_df["text_id"]

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_test_df["full_text"] = test_df["full_text"]

In [ ]:
cudf_train_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train_df["text_id"] = train_df["text_id"]

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train_df["full_text"] = train_df["full_text"]

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train_df["grammar"] = train_df["grammar"]

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train_df["conventions"] = train_df["conventions"]

In [4]:
%%time
### cell 1 ###

factor = 500
if (
    "IREWR_LESS_REPLICATION" in os.environ
    and os.environ["IREWR_LESS_REPLICATION"] == "True"
):
    factor = factor // 5
train_df = pd.concat([train_df] * factor)
test_df = pd.concat([test_df] * factor)
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1955500 entries, 0 to 3910
Data columns (total 8 columns):
 #   Column       Dtype
---  ------       -----
 0   text_id      object
 1   full_text    object
 2   cohesion     float64
 3   syntax       float64
 4   vocabulary   float64
 5   phraseology  float64
 6   grammar      float64
 7   conventions  float64
dtypes: float64(6), object(2)
memory usage: 134.3+ MB
CPU times: user 40.8 ms, sys: 63.9 ms, total: 105 ms
Wall time: 104 ms

In [ ]:
cudf_test_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_post 1 ##
cudf_test_df["text_id"] = test_df["text_id"]

In [ ]:
%%time
## Transfer_post 1 ##
cudf_test_df["full_text"] = test_df["full_text"]

In [ ]:
cudf_train_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_post 1 ##
cudf_train_df["text_id"] = train_df["text_id"]

In [ ]:
%%time
## Transfer_post 1 ##
cudf_train_df["full_text"] = train_df["full_text"]

In [ ]:
%%time
## Transfer_post 1 ##
cudf_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_post 1 ##
cudf_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_post 1 ##
cudf_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_post 1 ##
cudf_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_post 1 ##
cudf_train_df["grammar"] = train_df["grammar"]

In [ ]:
%%time
## Transfer_post 1 ##
cudf_train_df["conventions"] = train_df["conventions"]

Let's see a row from each dataset.

In [ ]:
cudf_train_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 2 ##
cudf_train_df["text_id"] = train_df["text_id"]

In [ ]:
%%time
## Transfer_pre 2 ##
cudf_train_df["full_text"] = train_df["full_text"]

In [ ]:
%%time
## Transfer_pre 2 ##
cudf_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_pre 2 ##
cudf_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_pre 2 ##
cudf_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_pre 2 ##
cudf_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_pre 2 ##
cudf_train_df["grammar"] = train_df["grammar"]

In [ ]:
%%time
## Transfer_pre 2 ##
cudf_train_df["conventions"] = train_df["conventions"]

In [5]:
%%time
### cell 2 ###

train_df.head()

CPU times: user 215 µs, sys: 34 µs, total: 249 µs
Wall time: 193 µs

,text_id,full_text,cohesion,syntax,vocabulary,phraseology,grammar,conventions
0,0016926B079C,I think that students would benefit from learn...,3.5,3.5,3.0,3.0,4.0,3.0
1,0022683E9EA5,When a problem is a change you have to let it ...,2.5,2.5,3.0,2.0,2.0,2.5
2,00299B378633,"Dear, Principal\n\nIf u change the school poli...",3.0,3.5,3.0,3.0,3.0,2.5
3,003885A45F42,The best time in life is when you become yours...,4.5,4.5,4.5,4.5,4.0,5.0
4,0049B1DF5CCC,Small act of kindness can impact in other peop...,2.5,3.0,3.0,3.0,2.5,2.5

In [ ]:
cudf_test_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 3 ##
cudf_test_df["text_id"] = test_df["text_id"]

In [ ]:
%%time
## Transfer_pre 3 ##
cudf_test_df["full_text"] = test_df["full_text"]

In [6]:
%%time
### cell 3 ###

test_df.head()

CPU times: user 52 µs, sys: 8 µs, total: 60 µs
Wall time: 63.4 µs

        text_id                                          full_text
0  0000C359D63E  when a person has no experience on a job their...
1  000BAD50D026  Do you think students would benefit from being...
2  00367BB2546B  Thomas Jefferson once states that "it is wonde...
0  0000C359D63E  when a person has no experience on a job their...
1  000BAD50D026  Do you think students would benefit from being...

Then the size of each dataset.

In [ ]:
cudf_test_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 4 ##
cudf_test_df["text_id"] = test_df["text_id"]

In [ ]:
%%time
## Transfer_pre 4 ##
cudf_test_df["full_text"] = test_df["full_text"]

In [ ]:
cudf_train_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 4 ##
cudf_train_df["text_id"] = train_df["text_id"]

In [ ]:
%%time
## Transfer_pre 4 ##
cudf_train_df["full_text"] = train_df["full_text"]

In [ ]:
%%time
## Transfer_pre 4 ##
cudf_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_pre 4 ##
cudf_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_pre 4 ##
cudf_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_pre 4 ##
cudf_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_pre 4 ##
cudf_train_df["grammar"] = train_df["grammar"]

In [ ]:
%%time
## Transfer_pre 4 ##
cudf_train_df["conventions"] = train_df["conventions"]

In [7]:
%%time
### cell 4 ###

len(train_df), len(test_df)

CPU times: user 8 µs, sys: 1 µs, total: 9 µs
Wall time: 11.7 µs

(1955500, 1500)

In [8]:
%%time
### cell 5 ###

LABEL_COLUMNS = [
    "cohesion",
    "syntax",
    "vocabulary",
    "phraseology",
    "grammar",
    "conventions",
]

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.96 µs

# Text Examples

## Random Examples

In [ ]:
cudf_train_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 6 ##
cudf_train_df["text_id"] = train_df["text_id"]

In [ ]:
%%time
## Transfer_pre 6 ##
cudf_train_df["full_text"] = train_df["full_text"]

In [ ]:
%%time
## Transfer_pre 6 ##
cudf_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_pre 6 ##
cudf_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_pre 6 ##
cudf_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_pre 6 ##
cudf_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_pre 6 ##
cudf_train_df["grammar"] = train_df["grammar"]

In [ ]:
%%time
## Transfer_pre 6 ##
cudf_train_df["conventions"] = train_df["conventions"]

In [9]:
%%time
### cell 6 ###

texts = train_df.sample(frac=1, random_state=420).head(4)

CPU times: user 333 ms, sys: 64.1 ms, total: 397 ms
Wall time: 396 ms

## Lowest Scoring Examples

In [ ]:
cudf_train_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 7 ##
cudf_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_pre 7 ##
cudf_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_pre 7 ##
cudf_train_df["conventions"] = train_df["conventions"]

In [ ]:
%%time
## Transfer_pre 7 ##
cudf_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_pre 7 ##
cudf_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_pre 7 ##
cudf_train_df["grammar"] = train_df["grammar"]

In [10]:
%%time
### cell 7 ###

train_df["total_score"] = train_df[LABEL_COLUMNS].sum(axis=1)
lowest_df = train_df.sort_values("total_score").head(4)

CPU times: user 524 ms, sys: 111 ms, total: 636 ms
Wall time: 634 ms

In [ ]:
cudf_train_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_post 7 ##
cudf_train_df["total_score"] = train_df["total_score"]

## Highest Scoring Examples

In [ ]:
cudf_train_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 8 ##
cudf_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_pre 8 ##
cudf_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_pre 8 ##
cudf_train_df["conventions"] = train_df["conventions"]

In [ ]:
%%time
## Transfer_pre 8 ##
cudf_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_pre 8 ##
cudf_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_pre 8 ##
cudf_train_df["total_score"] = train_df["total_score"]

In [ ]:
%%time
## Transfer_pre 8 ##
cudf_train_df["grammar"] = train_df["grammar"]

In [11]:
%%time
### cell 8 ###

train_df["total_score"] = train_df[LABEL_COLUMNS].sum(axis=1)
highest_df = train_df.sort_values("total_score", ascending=False).head(4)

CPU times: user 535 ms, sys: 87.9 ms, total: 623 ms
Wall time: 622 ms

# Text Overview

## Word Count

In [ ]:
cudf_train_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 9 ##
cudf_train_df["full_text"] = train_df["full_text"]

In [12]:
%%time
### cell 9 ###


train_df["word_count"] = train_df.full_text.apply(lambda x: len(x.split()))

CPU times: user 38.9 s, sys: 52.1 ms, total: 38.9 s
Wall time: 38.9 s

In [ ]:
cudf_train_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_post 9 ##
cudf_train_df["word_count"] = train_df["word_count"]

Mean word count:

In [ ]:
cudf_train_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 10 ##
cudf_train_df["word_count"] = train_df["word_count"]

In [13]:
%%time
### cell 10 ###

train_df["word_count"].mean()

CPU times: user 3.13 ms, sys: 0 ns, total: 3.13 ms
Wall time: 2.78 ms

430.4929685502429

Max word count:

In [ ]:
cudf_train_df = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 11 ##
cudf_train_df["word_count"] = train_df["word_count"]

In [14]:
%%time
### cell 11 ###

train_df["word_count"].max()

CPU times: user 964 µs, sys: 846 µs, total: 1.81 ms
Wall time: 1.45 ms

1260