In [1]:
%load_ext cudf.pandas

In [2]:
import sys, os

sys.path.insert(0, os.path.abspath("/home/ElasticNotebook"))
%load_ext ElasticNotebook
from elastic.core.common.pandas import compare_df
import pickle
import cudf

Enabled rmm statistics

# Imports

In [3]:
import numpy as np
import os

if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    # STEFANOS: Import Modin Pandas
    import os

    os.environ["MODIN_ENGINE"] = "ray"
    import ray

    ray.init(
        num_cpus=int(os.environ["MODIN_CPUS"]),
        runtime_env={"env_vars": {"__MODIN_AUTOIMPORT_PANDAS__": "1"}},
    )
    import modin.pandas as pd
else:
    # STEFANOS: Import regular Pandas
    import pandas as pd
import time

# Load Data

In [4]:
%%time
### cell 0 ###

train_df = pd.read_csv(
    "/home/dias-benchmarks/notebooks/lextoumbourou/feedback3-eda-hf-custom-trainer-sift/input/feedback-prize-english-language-learning/train.csv"
)
test_df = pd.read_csv(
    "/home/dias-benchmarks/notebooks/lextoumbourou/feedback3-eda-hf-custom-trainer-sift/input/feedback-prize-english-language-learning/test.csv"
)

CPU times: user 46.3 ms, sys: 80.3 ms, total: 127 ms
Wall time: 116 ms

In [ ]:
pd_test_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 0 ##
pd_test_df["text_id"] = test_df["text_id"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_test_df["full_text"] = test_df["full_text"]

In [ ]:
pd_train_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 0 ##
pd_train_df["text_id"] = train_df["text_id"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_train_df["full_text"] = train_df["full_text"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_train_df["grammar"] = train_df["grammar"]

In [ ]:
%%time
## Transfer_post 0 ##
pd_train_df["conventions"] = train_df["conventions"]

# -- STEFANOS -- Replicate Data

In [ ]:
pd_test_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 1 ##
pd_test_df["text_id"] = test_df["text_id"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_test_df["full_text"] = test_df["full_text"]

In [ ]:
pd_train_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 1 ##
pd_train_df["text_id"] = train_df["text_id"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_train_df["full_text"] = train_df["full_text"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_train_df["grammar"] = train_df["grammar"]

In [ ]:
%%time
## Transfer_pre 1 ##
pd_train_df["conventions"] = train_df["conventions"]

In [5]:
%%time
### cell 1 ###

factor = 500
if (
    "IREWR_LESS_REPLICATION" in os.environ
    and os.environ["IREWR_LESS_REPLICATION"] == "True"
):
    factor = factor // 5
train_df = pd.concat([train_df] * factor)
test_df = pd.concat([test_df] * factor)
train_df.info()

<class 'cudf.core.dataframe.DataFrame'>
Index: 1955500 entries, 0 to 3910
Data columns (total 8 columns):
 #   Column       Dtype
---  ------       -----
 0   text_id      object
 1   full_text    object
 2   cohesion     float64
 3   syntax       float64
 4   vocabulary   float64
 5   phraseology  float64
 6   grammar      float64
 7   conventions  float64
dtypes: float64(6), object(2)
memory usage: 4.4+ GB
CPU times: user 780 ms, sys: 148 ms, total: 928 ms
Wall time: 871 ms

In [ ]:
pd_test_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 1 ##
pd_test_df["text_id"] = test_df["text_id"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_test_df["full_text"] = test_df["full_text"]

In [ ]:
pd_train_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 1 ##
pd_train_df["text_id"] = train_df["text_id"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_train_df["full_text"] = train_df["full_text"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_train_df["grammar"] = train_df["grammar"]

In [ ]:
%%time
## Transfer_post 1 ##
pd_train_df["conventions"] = train_df["conventions"]

Let's see a row from each dataset.

In [ ]:
pd_train_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 2 ##
pd_train_df["text_id"] = train_df["text_id"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_train_df["full_text"] = train_df["full_text"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_train_df["grammar"] = train_df["grammar"]

In [ ]:
%%time
## Transfer_pre 2 ##
pd_train_df["conventions"] = train_df["conventions"]

In [6]:
%%time
### cell 2 ###

train_df.head()

CPU times: user 2.12 ms, sys: 8.09 ms, total: 10.2 ms
Wall time: 9.71 ms

,text_id,full_text,cohesion,syntax,vocabulary,phraseology,grammar,conventions
0,0016926B079C,I think that students would benefit from learn...,3.5,3.5,3.0,3.0,4.0,3.0
1,0022683E9EA5,When a problem is a change you have to let it ...,2.5,2.5,3.0,2.0,2.0,2.5
2,00299B378633,"Dear, Principal\n\nIf u change the school poli...",3.0,3.5,3.0,3.0,3.0,2.5
3,003885A45F42,The best time in life is when you become yours...,4.5,4.5,4.5,4.5,4.0,5.0
4,0049B1DF5CCC,Small act of kindness can impact in other peop...,2.5,3.0,3.0,3.0,2.5,2.5

In [ ]:
pd_test_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 3 ##
pd_test_df["text_id"] = test_df["text_id"]

In [ ]:
%%time
## Transfer_pre 3 ##
pd_test_df["full_text"] = test_df["full_text"]

In [7]:
%%time
### cell 3 ###

test_df.head()

CPU times: user 3.14 ms, sys: 7.68 ms, total: 10.8 ms
Wall time: 10.4 ms

        text_id                                          full_text
0  0000C359D63E  when a person has no experience on a job their...
1  000BAD50D026  Do you think students would benefit from being...
2  00367BB2546B  Thomas Jefferson once states that "it is wonde...
0  0000C359D63E  when a person has no experience on a job their...
1  000BAD50D026  Do you think students would benefit from being...

Then the size of each dataset.

In [ ]:
pd_test_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 4 ##
pd_test_df["text_id"] = test_df["text_id"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_test_df["full_text"] = test_df["full_text"]

In [ ]:
pd_train_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 4 ##
pd_train_df["text_id"] = train_df["text_id"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_train_df["full_text"] = train_df["full_text"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_train_df["grammar"] = train_df["grammar"]

In [ ]:
%%time
## Transfer_pre 4 ##
pd_train_df["conventions"] = train_df["conventions"]

In [8]:
%%time
### cell 4 ###

len(train_df), len(test_df)

CPU times: user 118 µs, sys: 52 µs, total: 170 µs
Wall time: 173 µs

(1955500, 1500)

In [9]:
%%time
### cell 5 ###

LABEL_COLUMNS = [
    "cohesion",
    "syntax",
    "vocabulary",
    "phraseology",
    "grammar",
    "conventions",
]

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.68 µs

# Text Examples

## Random Examples

In [ ]:
pd_train_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 6 ##
pd_train_df["text_id"] = train_df["text_id"]

In [ ]:
%%time
## Transfer_pre 6 ##
pd_train_df["full_text"] = train_df["full_text"]

In [ ]:
%%time
## Transfer_pre 6 ##
pd_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_pre 6 ##
pd_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_pre 6 ##
pd_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_pre 6 ##
pd_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_pre 6 ##
pd_train_df["grammar"] = train_df["grammar"]

In [ ]:
%%time
## Transfer_pre 6 ##
pd_train_df["conventions"] = train_df["conventions"]

In [10]:
%%time
### cell 6 ###

texts = train_df.sample(frac=1, random_state=420).head(4)

CPU times: user 162 ms, sys: 52.9 ms, total: 215 ms
Wall time: 211 ms

## Lowest Scoring Examples

In [ ]:
pd_train_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 7 ##
pd_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_pre 7 ##
pd_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_pre 7 ##
pd_train_df["conventions"] = train_df["conventions"]

In [ ]:
%%time
## Transfer_pre 7 ##
pd_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_pre 7 ##
pd_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_pre 7 ##
pd_train_df["grammar"] = train_df["grammar"]

In [11]:
%%time
### cell 7 ###

train_df["total_score"] = train_df[LABEL_COLUMNS].sum(axis=1)
lowest_df = train_df.sort_values("total_score").head(4)

CPU times: user 40.1 ms, sys: 59.7 ms, total: 99.7 ms
Wall time: 95.8 ms

In [ ]:
pd_train_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 7 ##
pd_train_df["total_score"] = train_df["total_score"]

## Highest Scoring Examples

In [ ]:
pd_train_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 8 ##
pd_train_df["syntax"] = train_df["syntax"]

In [ ]:
%%time
## Transfer_pre 8 ##
pd_train_df["vocabulary"] = train_df["vocabulary"]

In [ ]:
%%time
## Transfer_pre 8 ##
pd_train_df["conventions"] = train_df["conventions"]

In [ ]:
%%time
## Transfer_pre 8 ##
pd_train_df["cohesion"] = train_df["cohesion"]

In [ ]:
%%time
## Transfer_pre 8 ##
pd_train_df["phraseology"] = train_df["phraseology"]

In [ ]:
%%time
## Transfer_pre 8 ##
pd_train_df["total_score"] = train_df["total_score"]

In [ ]:
%%time
## Transfer_pre 8 ##
pd_train_df["grammar"] = train_df["grammar"]

In [12]:
%%time
### cell 8 ###

train_df["total_score"] = train_df[LABEL_COLUMNS].sum(axis=1)
highest_df = train_df.sort_values("total_score", ascending=False).head(4)

CPU times: user 62.3 ms, sys: 591 ms, total: 653 ms
Wall time: 623 ms

# Text Overview

## Word Count

In [ ]:
pd_train_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 9 ##
pd_train_df["full_text"] = train_df["full_text"]

In [13]:
%%time
### cell 9 ###


train_df["word_count"] = train_df.full_text.apply(lambda x: len(x.split()))

CPU times: user 41.2 s, sys: 1.23 s, total: 42.4 s
Wall time: 42.4 s

In [ ]:
pd_train_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 9 ##
pd_train_df["word_count"] = train_df["word_count"]

Mean word count:

In [ ]:
pd_train_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 10 ##
pd_train_df["word_count"] = train_df["word_count"]

In [14]:
%%time
### cell 10 ###

train_df["word_count"].mean()

CPU times: user 6.68 ms, sys: 146 µs, total: 6.82 ms
Wall time: 6.01 ms

430.4929685502429

Max word count:

In [ ]:
pd_train_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 11 ##
pd_train_df["word_count"] = train_df["word_count"]

In [15]:
%%time
### cell 11 ###

train_df["word_count"].max()

CPU times: user 6.14 ms, sys: 87 µs, total: 6.23 ms
Wall time: 4.61 ms

1260