In [1]:
import sys, os
sys.path.insert(0, os.path.abspath('/home/ElasticNotebook'))
%load_ext ElasticNotebook
from elastic.core.common.pandas import compare_df
import pickle
import cudf

Enabled rmm statistics

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load
import numpy as np # linear algebra
import os
# STEFANOS: Conditionally import Modin Pandas
if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    # STEFANOS: Import Modin Pandas
    import os
    os.environ["MODIN_ENGINE"] = "ray"
    import ray
    ray.init(num_cpus=int(os.environ['MODIN_CPUS']), runtime_env={'env_vars': {'__MODIN_AUTOIMPORT_PANDAS__': '1'}})
    import modin.pandas as pd
else:
    # STEFANOS: Import regular Pandas
    import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/home/dias-benchmarks/notebooks/mpwolke/just-you-wait-rishi-sunak/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/home/dias-benchmarks/notebooks/mpwolke/just-you-wait-rishi-sunak/input/latest-elected-uk-prime-minister-rishi-sunak/uk_pm.pkl
/home/dias-benchmarks/notebooks/mpwolke/just-you-wait-rishi-sunak/input/latest-elected-uk-prime-minister-rishi-sunak/uk_pm.feather
/home/dias-benchmarks/notebooks/mpwolke/just-you-wait-rishi-sunak/input/latest-elected-uk-prime-minister-rishi-sunak/uk_pm.parquet
/home/dias-benchmarks/notebooks/mpwolke/just-you-wait-rishi-sunak/input/latest-elected-uk-prime-minister-rishi-sunak/uk_pm.csv

#My Fair Lady "Just You Wait" At the beginning everything sounds nice.

"Just you wait, Rishi Sunak, just you wait

You'll be sorry but your tears will be too late

You'll be broke and I'll have money

Will I help you, don't be funny

Just you wait, Rishi Sunak, just you wait

Just you wait, Rishi Sunak 'till you're sick

And you screams to fetch a doctor double quick

I'll be off a second later

And go straight to the theater

Oh oh oh, Rishi Sunak, just you wait

Ooh, Rishi Sunak"

Lyrics by  Alan Jay Lerner / Frederick Loewe

In [3]:
import re
import string

import nltk
from nltk.probability import FreqDist
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# STEFANOS: Unneeded
# from wordcloud import WordCloud
from tqdm.auto import tqdm
import matplotlib.style as style
import time
style.use('fivethirtyeight')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/sahilbhatia/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/sahilbhatia/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/sahilbhatia/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

#Reading Parquet file

In [4]:
%%time
### cell 0 ###


train = pd.read_parquet('/home/dias-benchmarks/notebooks/mpwolke/just-you-wait-rishi-sunak/input/latest-elected-uk-prime-minister-rishi-sunak/uk_pm.parquet')

CPU times: user 230 ms, sys: 118 ms, total: 348 ms
Wall time: 226 ms

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['text'] = train['text']

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['username'] = train['username']

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['hashtags'] = train['hashtags']

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['created_at'] = train['created_at']

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['user followers count'] = train['user followers count']

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['replycount'] = train['replycount']

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['retweetcount'] = train['retweetcount']

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['likecount'] = train['likecount']

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['quotecount'] = train['quotecount']

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['language'] = train['language']

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['quotedtweet'] = train['quotedtweet']

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['inReplyToTweetId'] = train['inReplyToTweetId']

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['inReplyToUser'] = train['inReplyToUser']

In [ ]:
%%time
## Transfer_post 0 ##
cudf_train['mentionedUsers'] = train['mentionedUsers']

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['text'] = train['text']

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['username'] = train['username']

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['hashtags'] = train['hashtags']

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['created_at'] = train['created_at']

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['user followers count'] = train['user followers count']

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['replycount'] = train['replycount']

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['retweetcount'] = train['retweetcount']

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['likecount'] = train['likecount']

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['quotecount'] = train['quotecount']

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['language'] = train['language']

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['quotedtweet'] = train['quotedtweet']

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['inReplyToTweetId'] = train['inReplyToTweetId']

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['inReplyToUser'] = train['inReplyToUser']

In [ ]:
%%time
## Transfer_pre 1 ##
cudf_train['mentionedUsers'] = train['mentionedUsers']

In [5]:
%%time
### cell 1 ###

train.head()

CPU times: user 285 µs, sys: 52 µs, total: 337 µs
Wall time: 340 µs

,text,username,hashtags,created_at,user followers count,replycount,retweetcount,likecount,quotecount,language,quotedtweet,inReplyToTweetId,inReplyToUser,mentionedUsers
id,,,,,,,,,,,,,,
1584696134693711873,@BritIndianVoice @RishiSunak #RishiSunak is #B...,IsmailYSyed,"['RishiSunak', 'BritishHindu', 'Pakistani', 'P...",2022-10-24 23:59:35+00:00,393,0,0,0,0,en,<NA>,1.584541e+18,https://twitter.com/BritIndianVoice,@BritIndianVoice @RishiSunak #RishiSunak is #B...
1584696057841098752,#RishiSunak is the richest Tory MP in history....,AdameMedia,['RishiSunak'],2022-10-24 23:59:17+00:00,9830,3,23,68,4,en,<NA>,NaN,<NA>,#RishiSunak is the richest Tory MP in history....
1584695906091536385,#RishiSunak,ROHITKU96224077,['RishiSunak'],2022-10-24 23:58:40+00:00,3,0,0,0,0,qht,<NA>,NaN,<NA>,#RishiSunak
1584695822658441217,A mountain full of money and a knowledge of pr...,Parisistas,['RishiSunak'],2022-10-24 23:58:21+00:00,0,0,0,0,0,en,<NA>,NaN,<NA>,A mountain full of money and a knowledge of pr...
1584695640696946688,@trussliz @RishiSunak Chance was been given as...,baboo_prasant,['RishiSunak'],2022-10-24 23:57:37+00:00,14,0,0,0,0,en,<NA>,1.584546e+18,https://twitter.com/trussliz,@trussliz @RishiSunak Chance was been given as...

#Or you can have a csv version

In [6]:
%%time
### cell 2 ###

df = pd.read_csv("/home/dias-benchmarks/notebooks/mpwolke/just-you-wait-rishi-sunak/input/latest-elected-uk-prime-minister-rishi-sunak/uk_pm.csv", delimiter=',', encoding='utf8')
pd.set_option('display.max_columns', None)
df.tail()

CPU times: user 758 ms, sys: 39.9 ms, total: 798 ms
Wall time: 796 ms

,id,text,username,hashtags,created_at,user followers count,replycount,retweetcount,likecount,quotecount,language,quotedtweet,inReplyToTweetId,inReplyToUser,mentionedUsers
113573,1584553348736421888,@JackBarbour_ @piersmorgan @RishiSunak The man...,aqeelone22,NaN,2022-10-24 14:32:12+00:00,1162,0,0,0,0,en,NaN,1.584532e+18,https://twitter.com/JackBarbour_,@JackBarbour_ @piersmorgan @RishiSunak The man...
113574,1584553348677525505,@Jacob_Rees_Mogg @RishiSunak Let's hope you're...,EddieThornley,NaN,2022-10-24 14:32:12+00:00,97,0,0,0,0,en,NaN,1.584539e+18,https://twitter.com/Jacob_Rees_Mogg,@Jacob_Rees_Mogg @RishiSunak Let's hope you're...
113575,1584553348597895168,@sajidjavid @RishiSunak Desperate call for a d...,pedleysjohn,['ToriesUnfitToGovern'],2022-10-24 14:32:12+00:00,2484,0,0,0,0,en,NaN,1.584401e+18,https://twitter.com/sajidjavid,@sajidjavid @RishiSunak Desperate call for a d...
113576,1584553348132397056,@SkyNews Rulling Party needs a strong oppositi...,KarobiVC,NaN,2022-10-24 14:32:12+00:00,392,0,0,0,0,en,NaN,1.584512e+18,https://twitter.com/SkyNews,@SkyNews Rulling Party needs a strong oppositi...
113577,1584553347998105600,@trussliz @RishiSunak Liz Truss has won the ma...,sands_hill,NaN,2022-10-24 14:32:12+00:00,4,0,0,0,0,en,NaN,1.584546e+18,https://twitter.com/trussliz,@trussliz @RishiSunak Liz Truss has won the ma...

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 3 ##
cudf_train['likecount'] = train['likecount']

In [7]:
%%time
### cell 3 ###

#Code by Leon Wolber https://www.kaggle.com/leonwolber/reddit-nlp-topic-modeling-prediction

print(len(train[train['likecount'] < 500]), 'tweets with less than 500 dislikes')
print(len(train[train['likecount'] > 500]), 'tweets with more than 500 dislikes')

113332 tweets with less than 500 dislikes
246 tweets with more than 500 dislikes
CPU times: user 40.5 ms, sys: 51 µs, total: 40.5 ms
Wall time: 39.9 ms

#Tweet with more comments???? I'm making my Wine Reviews (aka drinking)

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 4 ##
cudf_train['likecount'] = train['likecount']

In [8]:
%%time
### cell 4 ###

#Code by Leon Wolber https://www.kaggle.com/leonwolber/reddit-nlp-topic-modeling-prediction

# video with the most comments

train[train['likecount'] == train['likecount'].max()]['text'].iloc[0]

CPU times: user 1.72 ms, sys: 284 µs, total: 2 ms
Wall time: 1.5 ms

"Warmest congratulations @RishiSunak! As you become UK PM, I look forward to working closely together on global issues, and implementing Roadmap 2030. Special Diwali wishes to the 'living bridge' of UK Indians, as we transform our historic ties into a modern partnership."

#We don't have DISLIKES yet? Just wait Prime Minister!

In [9]:
%%time
### cell 5 ###

#Code by Leon Wolber https://www.kaggle.com/leonwolber/reddit-nlp-topic-modeling-prediction

def remove_line_breaks(text):
    text = text.replace('\r', ' ').replace('\n', ' ')
    return text

#remove punctuation
def remove_punctuation(text):
    re_replacements = re.compile("__[A-Z]+__")  # such as __NAME__, __LINK__
    re_punctuation = re.compile("[%s]" % re.escape(string.punctuation))
    '''Escape all the characters in pattern except ASCII letters and numbers'''
    tokens = word_tokenize(text)
    tokens_zero_punctuation = []
    for token in tokens:
        if not re_replacements.match(token):
            token = re_punctuation.sub(" ", token)
        tokens_zero_punctuation.append(token)
    return ' '.join(tokens_zero_punctuation)

def remove_special_characters(text):
    text = re.sub('[^a-zA-z0-9\s]', '', text)
    return text

def lowercase(text):
    text_low = [token.lower() for token in word_tokenize(text)]
    return ' '.join(text_low)

def remove_stopwords(text):
    stop = set(stopwords.words('english'))
    word_tokens = nltk.word_tokenize(text)
    text = " ".join([word for word in word_tokens if word not in stop])
    return text

#remobe one character words
def remove_one_character_words(text):
    '''Remove words from dataset that contain only 1 character'''
    text_high_use = [token for token in word_tokenize(text) if len(token)>1]      
    return ' '.join(text_high_use)   
    
#%%
# Stemming with 'Snowball stemmer" package
def stem(text):
    stemmer = nltk.stem.snowball.SnowballStemmer('english')
    text_stemmed = [stemmer.stem(token) for token in word_tokenize(text)]        
    return ' '.join(text_stemmed)

def lemma(text):
    wordnet_lemmatizer = WordNetLemmatizer()
    word_tokens = nltk.word_tokenize(text)
    text_lemma = " ".join([wordnet_lemmatizer.lemmatize(word) for word in word_tokens])       
    return ' '.join(text_lemma)


#break sentences to individual word list
def sentence_word(text):
    word_tokens = nltk.word_tokenize(text)
    return word_tokens
#break paragraphs to sentence token 
def paragraph_sentence(text):
    sent_token = nltk.sent_tokenize(text)
    return sent_token    


def tokenize(text):
    """Return a list of words in a text."""
    return re.findall(r'\w+', text)

def remove_numbers(text):
    no_nums = re.sub(r'\d+', '', text)
    return ''.join(no_nums)



def clean_text(text):
    _steps = [
    remove_line_breaks,
    remove_one_character_words,
    remove_special_characters,
    lowercase,
    remove_punctuation,
    remove_stopwords,
    stem,
    remove_numbers
]
    for step in _steps:
        text=step(text)
    return text   
#%%

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 8.82 µs

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 6 ##
cudf_train['text'] = train['text']

In [10]:
%%time
### cell 6 ###

#https://stackoverflow.com/questions/55557004/getting-attributeerror-float-object-has-no-attribute-replace-error-while
#To avoid with tqdm AttributeError: 'float' object has no attribute

train["text"] = train["text"].astype(str)
train["text"] = [x.replace(':',' ') for x in train["text"]]

CPU times: user 31.3 ms, sys: 0 ns, total: 31.3 ms
Wall time: 30.3 ms

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_post 6 ##
cudf_train['text'] = train['text']

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 7 ##
cudf_train['text'] = train['text']

In [11]:
%%time
### cell 7 ###

train['clean_text'] = pd.Series([clean_text(i) for i in tqdm(train['text'])])

  0%|          | 0/113578 [00:00<?, ?it/s]

CPU times: user 1min 45s, sys: 2 s, total: 1min 47s
Wall time: 1min 46s

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_post 7 ##
cudf_train['clean_text'] = train['clean_text']

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 8 ##
cudf_train['clean_text'] = train['clean_text']

In [12]:
%%time
### cell 8 ###

words = train["clean_text"].values

CPU times: user 149 µs, sys: 4 µs, total: 153 µs
Wall time: 157 µs

In [13]:
%%time
### cell 9 ###

#Code by Leon Wolber https://www.kaggle.com/leonwolber/reddit-nlp-topic-modeling-prediction

ls = []

for i in words:
    ls.append(str(i))

CPU times: user 27 ms, sys: 0 ns, total: 27 ms
Wall time: 26.8 ms

In [14]:
%%time
### cell 10 ###

ls[:5]

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 6.91 µs

['nan', 'nan', 'nan', 'nan', 'nan']

In [15]:
# STEFANOS: Disable plotting
# #Code by Leon Wolber https://www.kaggle.com/leonwolber/reddit-nlp-topic-modeling-prediction

# # The wordcloud 
# plt.figure(figsize=(16,13))
# wc = WordCloud(background_color="lightblue", colormap='Set2', max_words=1000, max_font_size= 200,  width=1600, height=800)
# wc.generate(" ".join(ls))
# plt.title("Most discussed terms", fontsize=20)
# plt.imshow(wc.recolor( colormap= 'Set2' , random_state=17), alpha=0.98, interpolation="bilinear", )
# plt.axis('off')

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 11 ##
cudf_train['likecount'] = train['likecount']

In [16]:
%%time
### cell 11 ###

#Code by Leon Wolber https://www.kaggle.com/leonwolber/reddit-nlp-topic-modeling-prediction

most_pop = train.sort_values('likecount', ascending =False)[['text', 'likecount']].head(12)

most_pop['target1'] = most_pop['likecount']/1000

CPU times: user 61.4 ms, sys: 30 µs, total: 61.4 ms
Wall time: 61.2 ms

In [17]:
# STEFANOS: Disable plotting

# #Code by Leon Wolber https://www.kaggle.com/leonwolber/reddit-nlp-topic-modeling-prediction

# plt.figure(figsize = (30,35))

# sns.barplot(data = most_pop, y = 'text', x = 'target1', color = 'c')
# plt.xticks(fontsize=50, rotation=0)
# plt.yticks(fontsize=50, rotation=0)
# plt.xlabel('Votes in Thousands', fontsize = 21)
# plt.ylabel('')
# plt.title('Most popular tweets', fontsize = 50);

#I can't even read anything. Just: "Congratulations Rishi Sunak." Just Wait PM Sunak.

In [18]:
%%time
### cell 12 ###

import collections.abc
#gensim aliases to be done manually.
collections.Iterable = collections.abc.Iterable
collections.Mapping = collections.abc.Mapping
collections.MutableSet = collections.abc.MutableSet
collections.MutableMapping = collections.abc.MutableMapping
import gensim
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from nltk.stem import WordNetLemmatizer, SnowballStemmer
from nltk.stem.porter import *
import numpy as np
np.random.seed(2018)
import nltk

CPU times: user 80.2 ms, sys: 12 ms, total: 92.2 ms
Wall time: 91.7 ms

In [19]:
%%time
### cell 13 ###

stemmer = SnowballStemmer('english')

CPU times: user 13 µs, sys: 0 ns, total: 13 µs
Wall time: 16.9 µs

In [20]:
# STEFANOS: Disable. Connects to net.
# nltk.download('wordnet')

In [21]:
%%time
### cell 14 ###

#Code by Leon Wolber https://www.kaggle.com/leonwolber/reddit-nlp-topic-modeling-prediction

def lemmatize_stemming(text):
    return stemmer.stem(WordNetLemmatizer().lemmatize(text, pos='v'))

def preprocess(text):
    result = []
    for token in gensim.utils.simple_preprocess(text):
        if token not in gensim.parsing.preprocessing.STOPWORDS and len(token) > 3:
            result.append(lemmatize_stemming(token))
    return result

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 6.91 µs

#At the beginning, everything is so nice

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 15 ##
cudf_train['text'] = train['text']

In [22]:
%%time
### cell 15 ###

train['text'].iloc[2]

CPU times: user 88 µs, sys: 0 ns, total: 88 µs
Wall time: 91.3 µs

'#RishiSunak'

#I ran the snippet below to avoid error on the next snippet (after that one)

In [23]:
%%time
### cell 16 ###

import nltk
# STEFANOS: Disable. Connects to net.
# nltk.download('omw-1.4')

CPU times: user 16 µs, sys: 0 ns, total: 16 µs
Wall time: 19.3 µs

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 17 ##
cudf_train['text'] = train['text']

In [24]:
%%time
### cell 17 ###

#Code by Leon Wolber https://www.kaggle.com/leonwolber/reddit-nlp-topic-modeling-prediction

doc_sample = train['text'].iloc[1]
print('original document: ')

words = []

for word in doc_sample.split(' '):
    words.append(word)
    
    
print(words)
print('\n\n tokenized and lemmatized document: ')
print(preprocess(doc_sample))

original document:
['#RishiSunak', 'is', 'the', 'richest', 'Tory', 'MP', 'in', 'history.', 'His', 'wife', 'is', 'a', 'billionaire.', 'The', 'suggestion', 'that', 'he', 'is', 'representative', 'because', 'he', 'is', 'Asian', 'should', 'sound', 'ludicrous', 'to', 'your', 'ears.']


 tokenized and lemmatized document:

['rishisunak', 'richest', 'tori', 'histori', 'wife', 'billionair', 'suggest', 'repres', 'asian', 'sound', 'ludicr', 'ear']
CPU times: user 3.02 s, sys: 63.8 ms, total: 3.08 s
Wall time: 3.08 s

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 18 ##
cudf_train['text'] = train['text']

In [25]:
%%time
### cell 18 ###

train['text'] = train['text'].astype(str)

CPU times: user 6.7 ms, sys: 0 ns, total: 6.7 ms
Wall time: 6.05 ms

#Above it was suppose to be "clean_text"  Though I got an error.

In [ ]:
cudf_train = cudf.DataFrame()

In [ ]:
%%time
## Transfer_pre 19 ##
cudf_train['text'] = train['text']

In [26]:
%%time
### cell 19 ###

#Code by Leon Wolber https://www.kaggle.com/leonwolber/reddit-nlp-topic-modeling-prediction

words = []

for i in train['text']:
        words.append(i.split(' '))

CPU times: user 502 ms, sys: 36 ms, total: 538 ms
Wall time: 535 ms

In [27]:
%%time
### cell 20 ###

#Code by Leon Wolber https://www.kaggle.com/leonwolber/reddit-nlp-topic-modeling-prediction

dictionary = gensim.corpora.Dictionary(words)

count = 0
for k, v in dictionary.iteritems():
    print(k, v)
    count += 1
    if count > 10:
        break

0 #BritishHindu
1 #Pakistani
2 #RishiSunak
3 (#Pakistan Origin
4 (probably
5 @BritIndianVoice
6 @NadraPak
7 @RishiSunak
8 Also
9 Card)
10 He’s
CPU times: user 2.71 s, sys: 15.9 ms, total: 2.73 s
Wall time: 2.73 s

In [28]:
%%time
### cell 21 ###

bow_corpus = [dictionary.doc2bow(doc) for doc in words]
bow_corpus[4310]

CPU times: user 1.58 s, sys: 76.2 ms, total: 1.65 s
Wall time: 1.65 s

[(37, 1),
 (246, 1),
 (856, 1),
 (1017, 1),
 (1018, 1),
 (1806, 1),
 (3678, 1),
 (21373, 1),
 (24034, 1),
 (24035, 1),
 (24036, 1)]

In [29]:
%%time
### cell 22 ###

#Code by Leon Wolber https://www.kaggle.com/leonwolber/reddit-nlp-topic-modeling-prediction

bow_doc_4310 = bow_corpus[4310]

for i in range(len(bow_doc_4310)):
    print("Word {} (\"{}\") appears {} time.".format(bow_doc_4310[i][0], 
                                               dictionary[bow_doc_4310[i][0]], 
bow_doc_4310[i][1]))

Word 37 ("with") appears 1 time.
Word 246 ("Sunak") appears 1 time.
Word 856 ("now") appears 1 time.
Word 1017 ("Kenya") appears 1 time.
Word 1018 ("Obama") appears 1 time.
Word 1806 ("done") appears 1 time.
Word 3678 ("well") appears 1 time.
Word 21373 ("Started") appears 1 time.
Word 24034 ("(UK),") appears 1 time.
Word 24035 ("(US),") appears 1 time.
Word 24036 ("🇰🇪🤩

#RishiSunak") appears 1 time.
CPU times: user 129 µs, sys: 3 µs, total: 132 µs
Wall time: 114 µs

In [30]:
# STEFANOS: Disable the rest. It's ML.